apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: gitlab-managed-apps
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
  externalIPs:
    - 192.168.1.2
  type: ClusterIP
