kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: standard-local
  labels:
    type: host
spec:
  # set to empty to disable dynamic provisioning using StorageClass
  storageClassName: "standard-local"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
