smart_home:
  locale: en-US
  endpoint: https://api.amazonalexa.com/v3/events
  client_id: !secret alexa_client_id
  client_secret: !secret alexa_client_secret
  filter:
    include_entities:
      - light.aqaralampchildroom_light
      - light.ikeabulblamp_light
      - switch.washermachine_relay
      - switch.yamaha
      - switch.radio
      - switch.nc
      - switch.light1_relay
      - switch.light2_relay
      - switch.light3_relay
      - switch.blitzlivingroomcommod
      - switch.blitzlivingroomrtv
      - light.osrambulbsgrouptoilet
      - light.ikeabulbsgrouptoiletmirror
      - light.ikeabulbsgroupwardobe
      - light.philipsledoffice
      - switch.hdmi1
      - switch.hdmi2
      - light.lamp_kitchen
      - light.ikeabulbsgroupkitchen
      - light.ikeabulbsgroupanteroom1
      - light.ikeabulbsgroupanteroom2
      - scene.good_evening
      - scene.good_morning
      - scene.good_night
      - scene.cinema
      - media_player.tv
      - fan.air_purifier
      - binary_sensor.toiletdoor_contact
      - binary_sensor.maindoor_contact
      - binary_sensor.motionkitchen_occupancy
      - binary_sensor.motionkitchen2_occupancy
      - binary_sensor.motiontoilet_occupancy
      - binary_sensor.motionchildroom_occupancy
      - binary_sensor.livingroomwindow_contact
      - binary_sensor.livingroombalconywindow_contact
      - binary_sensor.childroomwindow_contact
      - binary_sensor.kitchenwindow_contact
      - binary_sensor.wardobewindow_contact
      - binary_sensor.doorbell
      # - climate.thermochildroom_climate
      # - climate.thermolivingroom_climate
      # - climate.thermokitchen_climate
      - vacuum.john
      - lock.maindoorlock
      - script.clean_home
      - script.clean_office
      - script.clean_kitchen
      - script.clean_toilet
      - script.clean_ante_room
      - script.clean_living_room
      - script.clean_child_room
  entity_config:
    light.aqaralampchildroom_light:
      name: "Lamp"
    light.ikeabulblamp_light:
      name: "Lamp"
    switch.washermachine_relay:
      name: "Washermachine"
    switch.yamaha:
      name: "Yamaha"
      display_categories: SWITCH
    switch.radio:
      name: "Radio"
      display_categories: SWITCH
    switch.nc:
      name: "NC"
      display_categories: SWITCH
    switch.light1_relay:
      name: "Light 1"
      display_categories: LIGHT
    switch.light2_relay:
      name: "Light 2"
      display_categories: LIGHT
    switch.light3_relay:
      name: "Light 3"
      display_categories: LIGHT
    switch.blitzlivingroomcommod:
      name: "Light Commode"
      display_categories: LIGHT
    switch.blitzlivingroomrtv:
      name: "Light RTV"
      display_categories: LIGHT
    light.osrambulbsgrouptoilet:
      name: "Light"
      display_categories: LIGHT
    light.ikeabulbsgrouptoiletmirror:
      name: "Mirror"
      display_categories: LIGHT
    light.ikeabulbsgroupwardobe:
      name: "Light"
      display_categories: LIGHT
    light.lamp_kitchen:
      name: "Light"
      display_categories: LIGHT
    light.ikeabulbsgroupkitchen:
      name: "Table"
      display_categories: LIGHT
    light.ikeabulbsgroupanteroom1:
      name: "Light 1"
      display_categories: LIGHT
    light.ikeabulbsgroupanteroom2:
      name: "Light 2"
      display_categories: LIGHT
    light.philipsledoffice:
      name: "Office Desk"
      display_categories: LIGHT
    switch.hdmi1:
      name: "HDMI1"
      display_categories: SWITCH
    switch.hdmi2:
      name: "HDMI2"
      display_categories: SWITCH        
    scene.good_evening:
      name: "Good Night"
      display_categories: SCENE
    scene.good_morning:
      name: "Good Morning"
      display_categories: SCENE
    scene.good_night:
      name: "Good Night"
      display_categories: SCENE
    scene.cinema:
      name: "Cinema"
      display_categories: SCENE
    script.clean_home:
      name: "Clean Home"
      display_categories: SCENE
    script.clean_office:
      name: "Clean Office"
      display_categories: SCENE
    script.clean_kitchen:
      name: "Clean Kitchen"
      display_categories: SCENE
    script.clean_toilet:
      name: "Clean Toilet"
      display_categories: SCENE
    script.clean_ante_room:
      name: "Clean Ante Room"
      display_categories: SCENE
    script.clean_living_room:
      name: "Clean Living Room"
      display_categories: SCENE
    script.clean_child_room:
      name: "Clean Child Room"
      display_categories: SCENE
    vacuum.john:
      name: "Vacuum Cleaner"
      display_categories: VACUUM_CLEANER
    # climate.thermochildroom_climate:
    #   name: "Thermo Child"
    #   display_categories: THERMOSTAT
    # climate.thermolivingroom_climate:
    #   name: "Thermo Living Room"
    #   display_categories: THERMOSTAT
    # climate.thermokitchen_climate:
    #   name: "Thermo Kitchen"
    #   display_categories: THERMOSTAT
    media_player.tv:
      name: TV
      display_categories: TV
    fan.air_purifier:
      name: Airpurifier
      display_categories: AIR_PURIFIER
    binary_sensor.toiletdoor_contact:
      name: Toilet Door
      display_categories: DOOR
    binary_sensor.maindoor_contact:
      name: Main Door
      display_categories: DOOR
    binary_sensor.motionkitchen_occupancy:
      name: Motion 
      display_categories: MOTION_SENSOR
    binary_sensor.motionkitchen2_occupancy:
      name: Motion
      display_categories: MOTION_SENSOR
    binary_sensor.motiontoilet_occupancy: 
      name: Motion
      display_categories: MOTION_SENSOR
    binary_sensor.motionchildroom_occupancy:  
      name: Motion
      display_categories: MOTION_SENSOR
    binary_sensor.livingroomwindow_contact:
      name: Window
      display_categories: CONTACT_SENSOR
    binary_sensor.livingroombalconywindow_contact:
      name: Balcony
      display_categories: CONTACT_SENSOR
    binary_sensor.childroomwindow_contact:
      name: Window
      display_categories: CONTACT_SENSOR
    binary_sensor.kitchenwindow_contact:
      name: Window
      display_categories: CONTACT_SENSOR
    binary_sensor.wardobewindow_contact:
      name: Window
      display_categories: CONTACT_SENSOR
    binary_sensor.doorbell:
      name: Doorbell
      display_categories: DOORBELL
    lock.maindoorlock:
      name: Door
      display_categories: SMARTLOCK

