## Configure a default setup
default_config:

logger:
  default: error
#  logs:
#    homeassistant.components.camera: debug
#    homeassistant.components.stream: debug#
#    homeassistant.components.ffmpeg: debug
#    homeassistant.components.unifiprotect: debug
#    homeassistant.components.go2rtc: debug
#    custom_components.unifiprotect: debug
#    pyunifiprotect: debug
#    uiprotect: debug

network:

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  customize: !include config/customize.yaml
  internal_url: "http://192.168.1.230:8123"
  allowlist_external_urls:
    - "https://home.olender.me"
zone: !include config/zone.yaml
http: !include config/http.yaml
script: !include config/scripts.yaml
alexa: !include config/alexa/alexa.yaml
sonos: !include config/sonos.yaml
homekit: !include config/homekit.yaml
recorder: !include config/recorder.yaml
prometheus: !include config/prometheus.yaml
automation: !include_dir_merge_list config/automation
template: !include config/template.yaml
command_line: !include config/command_line.yaml
adaptive_lighting: !include config/adaptive_lighting.yaml
