resources:
  - url: /local/zigbee2mqtt-networkmap.js?v=0.6.0
    type: module    
    
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js 
    type: module
  
title: Home
views:
  - badges: []
    in_card: true
    cards:
      # - type: weather-forecast
      #   show_forecast: false
      #   entity: weather.home
      #   name: 'Siemianowice'
        
      - type: entities
        show_header_toggle: false
        entities:
          - entity: scene.good_morning
          - entity: scene.good_evening
          - entity: scene.good_night
          - entity: scene.cinema

      - type: entities
        show_header_toggle: false
        header:
          type: custom:mini-graph-card
          name: Lights
          animate: false
          line_width: 3
          font_size: 75
          decimals: 1
          hours_to_show: 24
          font_size_header: 12
          line_color: '#04aaf5'
          points_per_hour: 1
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.light1_power
              name: Light 1
              show_legend: false
            - entity: sensor.light2_power
              name: Light 2
              show_legend: false
              show_state: true
              color: green
            - entity: sensor.light3_power
              name: Light 3 
              show_legend: false
              show_state: false
              color: purple 
        entities:
          - entity: light.aqaralampchildroom_light
            name: Child Room 1
          - entity: light.ikeabulbsgroupwardobe
            name: Child Room 2
          - entity: light.ikeabulblamp_light
            name: Living Room 
          - entity: switch.light1_relay
            name: Living Room 1
            state_color: on
          - entity: switch.light2_relay
            name: Living Room 2
            state_color: on
          - entity: switch.light3_relay
            name: Living Room 3
            state_color: on
          - entity: switch.blitzlivingroomrtv
            name: LED Rtv
            state_color: on
          - entity: switch.blitzlivingroomcommod
            name: LED Commode
            state_color: on
          - entity: light.ikeabulbsgroupkitchen
            name: Kitchen Table
          - entity: light.lamp_kitchen
            name: Kitchen 
          - entity: light.ikeabulbsgroupanteroom1
            name: Ante Room 1
          - entity: light.ikeabulbsgroupanteroom2
            name: Ante Room 2  
          - entity: light.osrambulbsgrouptoilet
            name: Toilet
          - entity: light.ikeabulbsgrouptoiletmirror
            name: Toilet Mirror

      - type: entities
        header:
          type: 'custom:mini-graph-card'
          name: RTV 
          line_width: 3
          font_size: 75
          decimals: 1
          hours_to_show: 24
          font_size_header: 12
          line_color: '#04aaf5'
          points_per_hour: 2
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.tv_power
              name: TV
              show_legend: false
              show_state: true
            - entity: sensor.yamaha_power
              name: Yamaha 
              show_legend: false
              show_state: true
              color: green
        show_header_toggle: false
        entities:
          - entity: media_player.tv
            state_color: on
          - entity: switch.yamaha
            state_color: on
          - entity: switch.radio
            state_color: on
          - entity: switch.hdmi1
            state_color: on
          - entity: switch.hdmi2
            state_color: on
          - entity: switch.nc
            state_color: on

      - type: entities
        header:
          type: custom:mini-graph-card
          entities:
            - entity: binary_sensor.childroomwindow_contact
              name: Childroom 1
              show_legend: false
            - entity: binary_sensor.wardobewindow_contact
              name: Child Room 2
              show_legend: false
            - entity: binary_sensor.kitchenwindow_contact
              name: Kitchen
              show_legend: false
              color: green
            - entity: binary_sensor.livingroombalconywindow_contact
              name: Living Room Balcony
              show_legend: false
            - entity: binary_sensor.livingroomwindow_contact
              name: Living Room
              show_legend: false
          name: Windows
          hours_to_show: 6
          points_per_hour: 6
          font_size: 75
          font_size_header: 12
          decimals: 1
          update_interval: 30
          aggregate_func: max
          line_width: 2
          smoothing: false
          show:
            fill: false
            labels: false
            points: false
          state_map:
            - value: "off"
              label: Closed
            - value: "on"
              label: Opened 
        show_header_toggle: false
        entities:
          - entity: binary_sensor.childroomwindow_contact
            state_color: on
            name: Child Room 1
          - entity: binary_sensor.wardobewindow_contact
            name: Child Room 2
            state_color: on
          - entity: binary_sensor.kitchenwindow_contact
            state_color: on
          - entity: binary_sensor.livingroombalconywindow_contact
            state_color: on
          - entity: binary_sensor.livingroomwindow_contact
            state_color: on

      - type: entities
        header:
          type: 'custom:mini-graph-card'
          name: Temperature 
          line_width: 3
          font_size: 75
          hours_to_show: 24
          font_size_header: 12
          decimals: 1
          points_per_hour: 2
          line_color: '#04aaf5'
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.thermostat_livingroom_temperature
              name: Living Room
              show_legend: false
              show_state: false
            - entity: sensor.thermostat_childroom_temperature
              name: Child Room
              show_legend: false
              show_state: false
              color: green
            - entity: sensor.thermostat_kitchen_temperature
              name: Kitchen
              show_legend: false
              show_state: false
              color: purple
        show_header_toggle: false
        entities:
          - entity: climate.thermolivingroom_climate
            name: Living Room
            state_color: on
          - entity: climate.thermochildroom_climate
            name: Child Room
            state_color: on
          - entity: climate.thermokitchen_climate
            name: Kitchen
            state_color: on
          - entity: switch.thermoseason
            name: Heat Season
            state_color: on
          - entity: sensor.mi_humidity
            name: Living Room
            state_color: on

      - type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.burze_dzis_net_heat_warning
            name: Heat warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_wind_warning
            name: Wind warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_storm_warning
            name: Storm warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_storms_nearby
            name: Storms nearby
            state_color: on

      - type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.doorbell
            state_color: on
          - entity: lock.maindoorlock
            name: Lock
            state_color: on
          - entity: binary_sensor.maindoor_contact
            state_color: on
          - entity: binary_sensor.toiletdoor_contact
            state_color: on
          - entity: device_tracker.iphone_luci_andrzej
            name: Andrzej
            state_color: on
          - entity: device_tracker.xiaomired_luci_ania
            name: Ania
            state_color: on  

      - type: entities
        header:
          type: custom:mini-graph-card
          entities:
            - entity: binary_sensor.motionkitchen_occupancy
              name: Anteroom
              show_legend: false
            - entity: binary_sensor.motionkitchen2_occupancy
              name: Kitchen
              show_legend: false
            - entity: binary_sensor.motiontoilet_occupancy
              name: Toilet
              show_legend: false
              color: green
            - entity: binary_sensor.motionchildroom_occupancy
              name: Childroom 1
              show_legend: false
            - entity: binary_sensor.motionchildroom2_occupancy
              name: Childroom 2
              show_legend: false
          name: Motions
          hours_to_show: 6
          points_per_hour: 6
          font_size: 75
          font_size_header: 12
          decimals: 1
          update_interval: 30
          aggregate_func: max
          line_width: 2
          smoothing: false
          show:
            fill: false
            labels: false
            points: false
          state_map:
            - value: "off"
              label: Clear
            - value: "on"
              label: Detected 
        show_header_toggle: false
        entities:
          - entity: binary_sensor.motionkitchen_occupancy
            name: Ante Room
            state_color: on
          - entity: binary_sensor.motionkitchen2_occupancy
            name: Kitchen 
            state_color: on
          - entity: binary_sensor.motiontoilet_occupancy
            name: Toilet
            state_color: on
          - entity: binary_sensor.motionchildroom_occupancy
            name: Child Room 1
            state_color: on
          - entity: binary_sensor.motionchildroom2_occupancy
            name: Child Room 2
            state_color: on

      - type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.leaksensorkitchen_water_leak
            state_color: on
          - entity: binary_sensor.leaksensortoilet_water_leak
            state_color: on

      - type: entities
        header:
          type: 'custom:mini-graph-card'
          name: Air
          line_width: 3
          font_size: 75
          hours_to_show: 24
          font_size_header: 12
          decimals: 1
          line_color: '#04aaf5'
          points_per_hour: 2
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.airly_aqi
              name: Outdoor
              color: green
              show_legend: false
            - entity: sensor.mi_aqi
              name: Home 
              show_legend: false
              show_state: true
        show_header_toggle: false
        entities:
          - entity: air_quality.airly
          - entity: fan.air_purifier
            state_color: on
          - entity: switch.airpurifiermax
            name: Air Max 
            state_color: on
          - entity: switch.airpurifierled
            name: LED
            state_color: on
          - entity: sensor.airly_aqi
            name: Outdoor
          - entity: sensor.mi_aqi
            name: Home

      - type: entities
        header:
          type: 'custom:mini-graph-card'
          name: AGD 
          line_width: 3
          font_size: 75
          hours_to_show: 24
          font_size_header: 12
          decimals: 1
          line_color: '#04aaf5'
          points_per_hour: 2
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.washermachine_power
              name: Washermachine
              show_legend: false
            - entity: sensor.fridge_power
              name: Fridge
              show_legend: false
              show_state: true
              color: green
            - entity: sensor.dishwasher_power
              name: Dishwasher 
              show_legend: false
              show_state: false
              color: purple
        show_header_toggle: false
        entities:
          - entity: switch.dishwasher_relay
            name: Dishwasher
            state_color: on
          - entity: switch.washermachine_relay
            name: Washermachine
            state_color: on
          - entity: switch.fridge_relay
            name: Fridge  
            state_color: on
          - entity: switch.tv_relay
            name: TV 
            state_color: on

      - type: vertical-stack
        in_card: true
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Download
                hour24: true
                points_per_hour: 1
                animate: false
                font_size: 75
                font_size_header: 12
                show:
                  fill: false
                  labels: false
                  points: false
                line_color: "#36a2eb"
                decimals: 1
                entities:
                  - sensor.speedtest_download
              - type: custom:mini-graph-card
                name: Upload
                hour24: true
                points_per_hour: 1
                animate: false
                font_size: 75
                font_size_header: 12
                line_color: "green"
                decimals: 1
                show:
                  fill: false
                  labels: false
                  points: false
                # font_size: 75
                # font_size_header: 12
                entities:
                  - sensor.speedtest_upload

    icon: 'mdi:home'
    panel: false
    path: default_view
    theme: default
    title: Home

  - badges: []
    visible:
      - user: 4b4a93638a344e758538b4f233cb5147
    cards:
      # - entities:
      #     - sensor.adguard_average_processing_speed
      #     - sensor.adguard_dns_queries
      #     - sensor.adguard_dns_queries_blocked_ratio
      #     - sensor.adguard_parental_control_blocked
      #     - sensor.adguard_safe_browsing_blocked
      #     - sensor.adguard_safe_searches_enforced
      #     - switch.adguard_protection
      #     - switch.adguard_safe_browsing
      #     - switch.adguard_filtering
      #     - switch.adguard_parental_control
      #   show_header_toggle: false
      #   type: entities

      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.zigbee2mqtt_bridge_state
          - entity: sensor.zigbee2mqtt_version
          - entity: switch.zigbee2mqtt_main_join
          - entity: timer.zigbee_permit_join

      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.redmi_note_4_wykryta_aktywnosc
            name: Activity

      # - type: picture-glance
      #   title: Camera
      #   entities: []
      #   camera_image: camera.front_door

      - type: map
        entities:
#          - device_tracker.iphone
          - device_tracker.redmi_note_4
        hours_to_show: 12
        dark_mode: true

    icon: 'mdi:shield-account'
    path: guard
    theme: default
    title: Guard

  - badges: []
    visible:
      - user: 4b4a93638a344e758538b4f233cb5147
    panel: true
    cards:
      - type: custom:zigbee2mqtt-networkmap
        entity: sensor.zigbee2mqtt_networkmap
        # the following are optional:
        name: Zigbbee2Mqtt
        mqtt_base_topic: zigbee2mqtt # if you change base_topic of Zigbee2mqtt, change it accordingly
        force: 2000 # decrease it to get smaller map if you have many devices
        node_size: 16
        font_size: 12
        link_width: 2
        height: 800 # height of the card
        # use this css config or use whatever css tech to change look and feel,
        # the same variable can also be used in Home Assistant themes, see https://www.home-assistant.io/components/frontend/#defining-themes
        css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(3, 169, 244, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #92d5f4;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(3, 169, 244, .7);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #03A9F4;
            --zigbee2mqtt-networkmap-arrow-color: rgba(3, 169, 244, .7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }      
    icon: 'mdi:access-point-network'
    path: zigbee
    theme: default
    title: Zigbee

  - badges: []
    visible:
      - user: 4b4a93638a344e758538b4f233cb5147
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.motionchildroom_battery
            name: Aqara motion - child room
          - entity: sensor.motionkitchen_battery
            name: Aqara motion - kitchen
          - entity: sensor.motionkitchen2_battery
            name: Aqara motion - kitchen 2
          - entity: sensor.motiontoilet_battery
            name: Aqata motion - toilet
          - entity: sensor.aqaraswitchanteroom1_battery
            name: Aqara switch - anteroom 1
          - entity: sensor.aqaraswitchchildroom_battery
            name: Aqara switch - childroom
          - entity: sensor.aqaraswitchchildroom2_battery
            name: Aqara switch 2 - childroom
          - entity: sensor.aqaraswitchkitchen1_battery
            name: Aqara switch - kitchen 1
          - entity: sensor.aqaraswitchkitchen2_battery
            name: Aqara switch - kitchen 2
          - entity: sensor.aqaraswitchlivingroom1_battery
            name: Aqara switch - living room 1
          - entity: sensor.aqaraswitchlivingroom2_battery
            name: Aqara switch - living room 2
          - entity: sensor.aqaraswitchtoilet1_battery
            name: Aqara switch - toilet 1
          - entity: sensor.aqaraswitchwardrobe_battery
            name: Aqara switch - wardobe
          - entity: sensor.kitchenwindow_battery
            name: Aqara window - kitchen
          - entity: sensor.leaksensorkitchen_battery
            name: Aqara leak - kitchen
          - entity: sensor.leaksensortoilet_battery
            name: Aqara leak - toilet
          - entity: sensor.livingroombalconywindow_battery
            name: Aqara window balcony - livingroom
          - entity: sensor.livingroomwindow_battery
            name: Aqara window - livingroom
          - entity: sensor.wardobewindow_battery
            name: Aqara window - wardobe
          - entity: sensor.maindoor_battery
            name: Aqara door - anteroom
          - entity: sensor.toiletdoor_battery
            name: Aqara door - toilet
          - entity: sensor.ringvibration_battery
            name: Aqara Doorbell - anteroom
          - entity: sensor.thermochildroom_battery
            name: Eurotronic thermo - child room
          - entity: sensor.thermolivingroom_battery
            name: Eurotronic thermo - livingroom
          - entity: sensor.thermokitchen_battery
            name: Eurotronic thermo - kitchen
          - entity: sensor.maindoorlock_battery
            name: Danalock - Anteroom

    icon: 'mdi:battery'
    panel: false
    path: Battery
    theme: default_view
    title: Battery


    