resources:
    
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js 
    type: module

  - url: /hacsfiles/lovelace-mushroom/mushroom.js
    type: module

  - url: /hacsfiles/kiosk-mode/kiosk-mode.js
    type: module

title: Home
views:
  - badges: []
    in_card: true
    cards:
      # - type: weather-forecast
      #   show_forecast: false
      #   entity: weather.home
      #   name: 'Siemianowice'
        
      - type: entities
        show_header_toggle: false
        entities:
          - entity: scene.good_morning
          - entity: scene.good_evening
          - entity: scene.good_night
          - entity: script.covers_open
            name: Blinds Open
          - entity: script.covers_close
            name: Blinds Close
          - entity: script.work_day
            name: Work Days

      - type: media-control
        entity: media_player.office

      - type: entities
        show_header_toggle: false
        entities:
          - entity: light.aqaralampchildroom_light
            name: Child Room 1
          - entity: light.group_6_wardobe_1
            name: Child Room 2
          - entity: light.ikeabulblamp_light
            name: Living Room 
          - entity: light.group_livingroom_1
            name: Living Room 1
            state_color: on
          - entity: light.lightlivingroomleftright_l1
            name: Living Room 2
            state_color: on
          - entity: light.lightlivingroomleftright_l2
            name: Living Room 3
            state_color: on
          - entity: switch.blitzlivingroomrtv
            name: LED Rtv
            state_color: on
          - entity: switch.blitzlivingroomcommod
            name: LED Commode
            state_color: on
          - entity: switch.blitzlivingroomglasscase
            name: LED Glass
            state_color: on
          - entity: light.lamp_kitchen
            name: Kitchen 
          - entity: light.group_2_anteroom_1
            name: Ante Room 1
          - entity: light.group_3_anteroom_2
            name: Ante Room 2  
          - entity: light.group_1_toilet_1
            name: Toilet
          - entity: light.group_5_toilet_2
            name: Toilet Mirror
          - entity: light.group_4_office_1
            name: Office
          - entity: light.philipsledoffice
            name: Office Desk
          - entity: light.philipsledofficeleft
            name: Office Left
          - entity: light.philipsledofficeright
            name: Office Right

      - type: entities
        header:
          type: 'custom:mini-graph-card'
          name: RTV 
          line_width: 3
          font_size: 75
          decimals: 1
          hours_to_show: 24
          font_size_header: 12
          line_color: '#04aaf5'
          points_per_hour: 2
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.tv_power
              name: TV
              show_legend: false
              show_state: true
            - entity: sensor.yamaha_power
              name: Yamaha 
              show_legend: false
              show_state: true
              color: green
        show_header_toggle: false
        entities:
          - entity: media_player.tv
            state_color: on
          - entity: switch.yamaha
            state_color: on
          - entity: switch.radio
            state_color: on
          - entity: switch.hdmi1
            state_color: on
          - entity: switch.hdmi2
            state_color: on
          - entity: switch.nc
            state_color: on

      - type: entities
        header:
          type: custom:mini-graph-card
          entities:
            - entity: binary_sensor.childroomwindow_contact
              name: Childroom 1
              show_legend: false
            - entity: binary_sensor.wardobewindow_contact
              name: Child Room 2
              show_legend: false
            - entity: binary_sensor.kitchenwindow_contact
              name: Kitchen
              show_legend: false
              color: green
            - entity: binary_sensor.livingroombalconywindow_contact
              name: Living Room Balcony
              show_legend: false
            - entity: binary_sensor.livingroomwindow_contact
              name: Living Room
              show_legend: false
          name: Windows
          hours_to_show: 6
          points_per_hour: 6
          font_size: 75
          font_size_header: 12
          decimals: 1
          update_interval: 30
          aggregate_func: max
          line_width: 2
          smoothing: false
          show:
            fill: false
            labels: false
            points: false
          state_map:
            - value: "off"
              label: Closed
            - value: "on"
              label: Opened 
        show_header_toggle: false
        entities:
          - entity: binary_sensor.childroomwindow_contact
            state_color: on
            name: Child Room 1
          - entity: binary_sensor.wardobewindow_contact
            name: Child Room 2
            state_color: on
          - entity: binary_sensor.kitchenwindow_contact
            state_color: on
          - entity: binary_sensor.livingroombalconywindow_contact
            state_color: on
          - entity: binary_sensor.livingroomwindow_contact
            state_color: on

      - type: entities
        entities:
          - entity: cover.blindslivingroomwindow1
            state_color: on
            name: Living Room 1
          - entity: cover.blindslivingroomwindow2
            state_color: on
            name: Living Room 2
          - entity: cover.blindslivingroomwindow3
            state_color: on
            name: Living Room 3
          - entity: cover.blindschildroomwindow1
            state_color: on
            name: Child Room 
          - entity: cover.blindsofficewindow1
            state_color: on
            name: Office 1
          - entity: cover.blindsofficewindow2
            state_color: on
            name: Office 2
          - entity: cover.blindskitchenwindow1
            state_color: on
            name: Kitchen

      - type: entities
        header:
          type: 'custom:mini-graph-card'
          name: Temperature 
          line_width: 3
          font_size: 75
          hours_to_show: 24
          font_size_header: 12
          decimals: 1
          points_per_hour: 2
          line_color: '#04aaf5'
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.thermostat_livingroom_temperature
              name: Living Room
              show_legend: false
              show_state: false
            - entity: sensor.thermostat_childroom_temperature
              name: Child Room
              show_legend: false
              show_state: false
              color: green
            - entity: sensor.thermostat_kitchen_temperature
              name: Kitchen
              show_legend: false
              show_state: false
              color: purple
        show_header_toggle: false
        entities:
          - entity: climate.thermolivingroom_climate
            name: Living Room
            state_color: on
          - entity: climate.thermochildroom_climate
            name: Child Room
            state_color: on
          - entity: climate.thermokitchen_climate
            name: Kitchen
            state_color: on
          - entity: switch.thermoseason
            name: Heat Season
            state_color: on
          - entity: switch.srealerts
            name: SRE Alerts
            state_color: on
          - entity: sensor.air_purifier_humidity
            name: Living Room
            state_color: on
          - entity: script.miio_turn_on_climate
            name: Climate ON/OFF
          - entity: script.miio_speed_climate
            name: Climate Speed
          - entity: script.miio_osc_climate
            name: Climate OSC
          - entity: sensor.pgnig_gas_sensor
            name: PGNiG
            state_color: on

      - type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.burze_dzis_net_ostrzezenie_upal
            name: Heat warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_ostrzezenie_wiatr
            name: Wind warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_ostrzezenie_burza
            name: Storm warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_ostrzezenie_aktywne_burza
            name: Storms nearby
            state_color: on

      - type: entities
        show_header_toggle: false
        entities:
          - entity: lock.maindoorlock
            name: Lock
            state_color: on
          - entity: binary_sensor.maindoor_contact
            state_color: on
          - entity: binary_sensor.toiletdoor_contact
            state_color: on
          - entity: sensor.home_andrzej
            name: Andrzej
            state_color: on  
          - entity: sensor.home_ania
            name: Ania
            state_color: on  

      - type: entities
        header:
          type: custom:mini-graph-card
          entities:
            - entity: binary_sensor.motionkitchen_occupancy
              name: Anteroom
              show_legend: false
            - entity: binary_sensor.motionkitchen2_occupancy
              name: Kitchen
              show_legend: false
            - entity: binary_sensor.motiontoilet_occupancy
              name: Toilet
              show_legend: false
              color: green
            - entity: binary_sensor.motionchildroom_occupancy
              name: Childroom 1
              show_legend: false
            - entity: binary_sensor.motionchildroom2_occupancy
              name: Childroom 2
              show_legend: false
          name: Motions
          hours_to_show: 6
          points_per_hour: 6
          font_size: 75
          font_size_header: 12
          decimals: 1
          update_interval: 30
          aggregate_func: max
          line_width: 2
          smoothing: false
          show:
            fill: false
            labels: false
            points: false
          state_map:
            - value: "off"
              label: Clear
            - value: "on"
              label: Detected 
        show_header_toggle: false
        entities:
          - entity: binary_sensor.motionkitchen_occupancy
            name: Ante Room
            state_color: on
          - entity: binary_sensor.motionkitchen2_occupancy
            name: Kitchen 
            state_color: on
          - entity: binary_sensor.motiontoilet_occupancy
            name: Toilet
            state_color: on
          - entity: binary_sensor.motionchildroom_occupancy
            name: Child Room 1
            state_color: on
          - entity: binary_sensor.motionchildroom2_occupancy
            name: Child Room 2
            state_color: on

      - type: entities
        show_header_toggle: false
        entities:
          - entity: binary_sensor.leaksensortoilet_water_leak
            state_color: on

      - type: entities
        header:
          type: 'custom:mini-graph-card'
          name: Air
          line_width: 3
          font_size: 75
          hours_to_show: 24
          font_size_header: 12
          decimals: 1
          line_color: '#04aaf5'
          points_per_hour: 2
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.i_lo_siemianowice_slaskie_pm2_5
              name: Outdoor
              color: green
              show_legend: false
            - entity: sensor.air_purifier_pm2_5
              name: Home 
              show_legend: false
              show_state: true
        show_header_toggle: false
        entities:
          - entity: fan.air_purifier
            state_color: on
          - entity: switch.air_purifier_led
            name: LED
            state_color: on
          - entity: sensor.i_lo_siemianowice_slaskie_pm2_5
            name: Outdoor
          - entity: sensor.air_purifier_pm2_5
            name: Home

      - type: entities
        header:
          type: 'custom:mini-graph-card'
          name: AGD 
          line_width: 3
          font_size: 75
          hours_to_show: 24
          font_size_header: 12
          decimals: 1
          line_color: '#04aaf5'
          points_per_hour: 2
          show:
            fill: false
            labels: false
            points: false
          entities:
            - entity: sensor.washermachine_power
              name: Washermachine
              show_legend: false
            - entity: sensor.fridge_power
              name: Fridge
              show_legend: false
              show_state: true
              color: green
            - entity: sensor.dishwasher_power
              name: Dishwasher 
              show_legend: false
              show_state: false
              color: purple
        show_header_toggle: false
        entities:
          - entity: switch.dishwasher_relay
            name: Dishwasher
            state_color: on
          - entity: switch.washermachine
            name: Washermachine
            state_color: on
          - entity: switch.fridge_relay
            name: Fridge  
            state_color: on
          - entity: switch.tv_relay
            name: TV 
            state_color: on

      - type: vertical-stack
        in_card: false
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Download
                hour24: true
                points_per_hour: 1
                animate: false
                font_size: 75
                font_size_header: 12
                show:
                  fill: false
                  labels: false
                  points: false
                line_color: "#36a2eb"
                decimals: 1
                entities:
                  - sensor.speedtest_download
              - type: custom:mini-graph-card
                name: Upload
                hour24: true
                points_per_hour: 1
                animate: false
                font_size: 75
                font_size_header: 12
                line_color: "green"
                decimals: 1
                show:
                  fill: false
                  labels: false
                  points: false
                # font_size: 75
                # font_size_header: 12
                entities:
                  - sensor.speedtest_upload

    icon: 'mdi:home'
    panel: false
    path: default_view
    theme: default
    title: Home

  - badges: []
    cards:     
      - type: entities
        header:
          type: custom:mini-graph-card
          entities:
            - entity: binary_sensor.vacuum_cleaning
              name: Vacuum
              show_legend: false
          name: Vacuum
          hours_to_show: 24
          points_per_hour: 2
          font_size: 75
          font_size_header: 12
          decimals: 1
          update_interval: 30
          aggregate_func: max
          line_width: 2
          smoothing: false
          show:
            fill: false
            labels: false
            points: false
          state_map:
            - value: "off"
              label: Docked
            - value: "on"
              label: Cleaning 
        show_header_toggle: false
        entities:
          - entity: vacuum.john
            name: John
          - entity: script.clean_home
            name: Home
          - entity: script.clean_office
            name: Office
          - entity: script.clean_kitchen
            name: Kitchen
          - entity: script.clean_toilet
            name: Toilet
          - entity: script.clean_ante_room
            name: Ante Room
          - entity: script.clean_living_room
            name: Living Room
          - entity: script.clean_child_room
            name: Child Room
          - entity: script.clean_white_floor
            name: White Floor

      - type: picture-entity
        entity: camera.xiaomi_cloud_map_extractor
        name: John



    icon: 'mdi:robot-vacuum'
    path: vacuum
    theme: default
    title: vacuum

  - badges: []
    visible:
      - user: 4b4a93638a344e758538b4f233cb5147
    panel: true
    cards:
      - type: map
        entities:
#          - device_tracker.iphone
          - device_tracker.samsung
        hours_to_show: 12
        dark_mode: true

    icon: 'mdi:shield-account'
    path: guard
    theme: default
    title: Guard   

  - badges: []
    visible:
      - user: 4b4a93638a344e758538b4f233cb5147
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.motionchildroom_battery
            name: Aqara motion - child room
          - entity: sensor.motionkitchen_battery
            name: Aqara motion - kitchen
          - entity: sensor.motionkitchen2_battery
            name: Aqara motion - kitchen 2
          - entity: sensor.motiontoilet_battery
            name: Aqata motion - toilet
          - entity: sensor.aqaraswitchanteroom1_battery
            name: Aqara switch - anteroom 1
          - entity: sensor.aqaraswitchchildroom_battery
            name: Aqara switch - childroom
          - entity: sensor.aqaraswitchchildroom2_battery
            name: Aqara switch 2 - childroom
          - entity: sensor.aqaraswitchkitchen1_battery
            name: Aqara switch - kitchen 1
          - entity: sensor.aqaraswitchkitchen2_battery
            name: Aqara switch - kitchen 2
          - entity: sensor.aqaraswitchlivingroom1_battery
            name: Aqara switch - living room 1
          - entity: sensor.aqaraswitchlivingroom2_battery
            name: Aqara switch - living room 2
          - entity: sensor.aqaraswitchtoilet1_battery
            name: Aqara switch - toilet 1
          - entity: sensor.aqaraswitchwardrobe_battery
            name: Aqara switch - wardobe
          - entity: sensor.kitchenwindow_battery
            name: Aqara window - kitchen
          - entity: sensor.leaksensorkitchen_battery
            name: Aqara leak - kitchen
          - entity: sensor.leaksensortoilet_battery
            name: Aqara leak - toilet
          - entity: sensor.livingroombalconywindow_battery
            name: Aqara window balcony - livingroom
          - entity: sensor.livingroomwindow_battery
            name: Aqara window - livingroom
          - entity: sensor.wardobewindow_battery
            name: Aqara window - wardobe
          - entity: sensor.maindoor_battery
            name: Aqara door - anteroom
          - entity: sensor.toiletdoor_battery
            name: Aqara door - toilet
          # - entity: sensor.ringvibration_battery
          #   name: Aqara Doorbell - anteroom
          - entity: sensor.thermochildroom_battery
            name: Eurotronic thermo - child room
          - entity: sensor.thermolivingroom_battery
            name: Eurotronic thermo - livingroom
          - entity: sensor.thermokitchen_battery
            name: Eurotronic thermo - kitchen
          - entity: sensor.maindoorlock_battery
            name: Danalock - Anteroom

    icon: 'mdi:battery'
    panel: false
    path: Battery
    theme: default_view
    title: Battery


