resources:
  - url: /local/zigbee2mqtt-networkmap.js?v=0.6.0
    type: module    
    
title: Home
views:
  - badges: []
    cards:
      - entity: weather.home
        type: weather-forecast
        name: 'Siemianowice'
        show_forecast: true
        attribute: humidity
        
      - entities:
          - entity: scene.good_morning
          - entity: scene.good_evening
          - entity: scene.good_night
          - entity: scene.cinema
        show_header_toggle: false
        type: entities

      - entities:
          - entity: light.aqaralampchildroom_light
            name: Child Room
          - entity: light.ikeabulblamp_light
            name: Living Room 
          - entity: switch.light1_relay
            name: Living Room 1
            state_color: on
          - entity: switch.light2_relay
            name: Living Room 2
            state_color: on
          - entity: switch.light3_relay
            name: Living Room 3
            state_color: on
          - entity: light.ikeabulbsgroupkitchen
            name: Kitchen Table
          - entity: light.lamp_kitchen
            name: Kitchen 
          - entity: light.ikeabulbsgroupanteroom1
            name: Ante Room 1
          - entity: light.ikeabulbsgroupanteroom2
            name: Ante Room 2  
          - entity: light.osrambulbsgrouptoilet
            name: Toilet
          - entity: light.ikeabulbsgrouptoiletmirror
            name: Toilet Mirror
          - entity: light.ikeabulbsgroupwardobe
            name: Wardobe
        show_header_toggle: false
        type: entities

      - entities:
          - entity: media_player.tv
            state_color: on
          - entity: light.yamaha
            state_color: on
          - entity: light.radio
            state_color: on
          - entity: light.hdmi1
            state_color: on
          - entity: light.hdmi2
            state_color: on
          - entity: light.nc
            state_color: on
        show_header_toggle: false
        type: entities

      - entities:
          - entity: binary_sensor.childroomwindow_contact
            state_color: on
          - entity: binary_sensor.kitchenwindow_contact
            state_color: on
          - entity: binary_sensor.livingroombalconywindow_contact
            state_color: on
          - entity: binary_sensor.livingroomwindow_contact
            state_color: on
          - entity: binary_sensor.wardobewindow_contact
            name: Wardobe
            state_color: on
        show_header_toggle: false
        type: entities

      - entities:
          - entity: climate.thermolivingroom_climate
            name: Living Room
            state_color: on
          - entity: climate.thermochildroom_climate
            name: Child Room
            state_color: on
          - entity: sensor.mi_temperature
            name: Living Room
            state_color: on
        show_header_toggle: false
        type: entities  
        
      - entities:
          - entity: binary_sensor.burze_dzis_net_heat_warning
            name: Heat warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_wind_warning
            name: Wind warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_storm_warning
            name: Storm warning
            state_color: on
          - entity: binary_sensor.burze_dzis_net_storms_nearby
            name: Storms nearby
            state_color: on
        show_header_toggle: false
        type: entities

      - entities:
          - entity: binary_sensor.doorbell
            state_color: on
          - entity: binary_sensor.toiletdoor_contact
            state_color: on
          - entity: binary_sensor.maindoor_contact
            state_color: on
          - entity: device_tracker.iphone_luci_andrzej
            name: Andrzej
            state_color: on
          - entity: device_tracker.xiaomired_luci_ania
            name: Ania
            state_color: on
        show_header_toggle: false
        type: entities   

      - entities:
          - entity: binary_sensor.motionkitchen_occupancy
            name: Ante Room
            state_color: on
          - entity: binary_sensor.motionkitchen2_occupancy
            name: Kitchen 
            state_color: on
          - entity: binary_sensor.motiontoilet_occupancy
            name: Toilet
            state_color: on
          - entity: binary_sensor.motionchildroom_occupancy
            name: Child Room
            state_color: on
        show_header_toggle: false
        type: entities

      - entities:
          - entity: binary_sensor.leaksensorkitchen_water_leak
            state_color: on
          - entity: binary_sensor.leaksensortoilet_water_leak
            state_color: on
        show_header_toggle: false
        type: entities

      - entities:
          - entity: air_quality.airly
          - entity: fan.air_purifier
            state_color: on
          - entity: switch.airpurifiermax
            name: Air Max 
            state_color: on
          - entity: switch.airpurifierled
            name: LED
            state_color: on
          - entity: sensor.airly_aqi
            name: Outdoor
          - entity: sensor.mi_aqi
            name: Home
        show_header_toggle: false
        type: entities  

      - entities:
          - entity: switch.dishwasher_relay
            name: Dishwasher
            state_color: on
          - entity: switch.washermachine_relay
            name: Washermachine
            state_color: on
          - entity: switch.fridge_relay
            name: Fridge  
            state_color: on
          - entity: switch.tv_relay
            name: TV 
            state_color: on
        show_header_toggle: false
        type: entities

    icon: 'mdi:home'
    panel: false
    path: default_view
    theme: default
    title: Home

  - badges: []
    cards:
      - entities:
          - sensor.adguard_average_processing_speed
          - sensor.adguard_dns_queries
          - sensor.adguard_dns_queries_blocked_ratio
          - sensor.adguard_parental_control_blocked
          - sensor.adguard_safe_browsing_blocked
          - sensor.adguard_safe_searches_enforced
          - switch.adguard_protection
          - switch.adguard_safe_browsing
          - switch.adguard_filtering
          - switch.adguard_parental_control
        show_header_toggle: false
        type: entities
        
      - entities:
          - entity: sensor.zigbee2mqtt_bridge_state
          - entity: sensor.zigbee2mqtt_version
          - entity: switch.zigbee2mqtt_main_join
          - entity: timer.zigbee_permit_join
        show_header_toggle: false
        type: entities

      - type: map
        entities:
#          - device_tracker.iphone
          - device_tracker.redmi_note_4
        hours_to_show: 12
        dark_mode: true

    icon: 'mdi:shield-account'
    path: guard
    theme: default
    title: Guard

  - badges: []
    panel: true
    cards:
      - type: custom:zigbee2mqtt-networkmap
        entity: sensor.zigbee2mqtt_networkmap
        # the following are optional:
        name: Zigbbee2Mqtt
        mqtt_base_topic: zigbee2mqtt # if you change base_topic of Zigbee2mqtt, change it accordingly
        force: 2000 # decrease it to get smaller map if you have many devices
        node_size: 16
        font_size: 12
        link_width: 2
        height: 800 # height of the card
        # use this css config or use whatever css tech to change look and feel,
        # the same variable can also be used in Home Assistant themes, see https://www.home-assistant.io/components/frontend/#defining-themes
        css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(3, 169, 244, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #92d5f4;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(3, 169, 244, .7);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #03A9F4;
            --zigbee2mqtt-networkmap-arrow-color: rgba(3, 169, 244, .7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }      
    icon: 'mdi:access-point-network'
    path: zigbee
    theme: default
    title: Zigbee

  - badges: []
    cards:
      - entities:
          - entity: scene.good_morning
          - entity: scene.good_evening
          - entity: scene.good_night
          - entity: scene.cinema
        show_header_toggle: false
        title: Scenes
        type: entities

# Anteroom
      - entities:
          - entity: light.ikeabulbsgroupanteroom1
            name: Light 1
          - entity: light.ikeabulbsgroupanteroom2
            name: Light 2  
          - entity: binary_sensor.maindoor_contact
            state_color: on
          - entity: binary_sensor.motionkitchen_occupancy
            name: Motion
            state_color: on
        show_header_toggle: false
        type: entities  
        title: Ante Room

# Living Room        
      - entities:
          - entity: light.ikeabulblamp_light
            name: Lamp 
          - entity: switch.light1_relay
            name: Light 1
            state_color: on
          - entity: switch.light2_relay
            name: Light 2
            state_color: on
          - entity: switch.light3_relay
            name: Light 3
            state_color: on
          - entity: media_player.tv
            name: TV
            state_color: on
          - entity: media_player.echo
            state_color: on
          - entity: light.yamaha
            state_color: on
          - entity: light.radio
            state_color: on
          - entity: light.hdmi1
            state_color: on
          - entity: light.hdmi2
            state_color: on
          - entity: light.nc
            state_color: on
          - entity: binary_sensor.livingroombalconywindow_contact
            name: Balcony
            state_color: on
          - entity: binary_sensor.livingroomwindow_contact
            name: Window
            state_color: on
          - entity: fan.air_purifier
            state_color: on
          - entity: climate.thermolivingroom_climate
            name: Thermostat
            state_color: on
        show_header_toggle: false
        type: entities
        title: Living Room

# Child room
      - entities:
          - entity: light.aqaralampchildroom_light
            name: Light
          - entity: binary_sensor.childroomwindow_contact
            state_color: on
            name: Window
          - entity: climate.thermochildroom_climate
            name: Thermostat
          - entity: binary_sensor.motionchildroom_occupancy
            name: Motion
            state_color: on
        show_header_toggle: false
        type: entities  
        title: Child Room

# Kitchen
      - entities:
          - entity: light.lamp_kitchen
            name: Light 
          - entity: light.ikeabulbsgroupkitchen
            name: Table
          - entity: binary_sensor.kitchenwindow_contact
            name: Window
            state_color: on
          - entity: binary_sensor.motionkitchen2_occupancy
            name: Motion 
            state_color: on  
          - entity: binary_sensor.leaksensorkitchen_water_leak
            state_color: on
            name: Leak          
        show_header_toggle: false
        type: entities  
        title: Kitchen

# Toilet
      - entities:
          - entity: light.osrambulbsgrouptoilet
            name: Light
          - entity: light.ikeabulbsgrouptoiletmirror
            name: Mirror
          - entity: binary_sensor.toiletdoor_contact
            state_color: on
            name: Door
          - entity: binary_sensor.motiontoilet_occupancy
            name: Motion
            state_color: on
          - entity: binary_sensor.leaksensortoilet_water_leak
            state_color: on
            name: Leak
          - entity: switch.washermachine_relay
            name: Washermachine
            state_color: on
        show_header_toggle: false
        type: entities  
        title: Toilet

# Wardobe
      - entities:
          - entity: light.ikeabulbsgroupwardobe
            name: Light
          - entity: binary_sensor.wardobewindow_contact
            name: Window
            state_color: on
        show_header_toggle: false
        type: entities  
        title: Wardobe

    icon: 'mdi:home-assistant'
    panel: false
    path: Rooms
    theme: default_view
    title: Rooms

  - badges: []
    cards:
      - entities:
          - entity: sensor.motionchildroom_battery
            name: Aqara motion - child room
          - entity: sensor.motionkitchen_battery
            name: Aqara motion - kitchen
          - entity: sensor.motionkitchen2_battery
            name: Aqara motion - kitchen 2
          - entity: sensor.motiontoilet_battery
            name: Aqata motion - toilet
          - entity: sensor.aqaraswitchanteroom1_battery
            name: Aqara switch - anteroom 1
          - entity: sensor.aqaraswitchchildroom_battery
            name: Aqara switch - childroom
          - entity: sensor.aqaraswitchchildroom2_battery
            name: Aqara switch 2 - childroom
          - entity: sensor.aqaraswitchkitchen1_battery
            name: Aqara switch - kitchen 1
          - entity: sensor.aqaraswitchkitchen2_battery
            name: Aqara switch - kitchen 2
          - entity: sensor.aqaraswitchlivingroom1_battery
            name: Aqara switch - living room 1
          - entity: sensor.aqaraswitchlivingroom2_battery
            name: Aqara switch - living room 2
          - entity: sensor.aqaraswitchtoilet1_battery
            name: Aqara switch - toilet 1
          - entity: sensor.aqaraswitchwardrobe_battery
            name: Aqara switch - wardobe
          - entity: sensor.kitchenwindow_battery
            name: Aqara window - kitchen
          - entity: sensor.leaksensorkitchen_battery
            name: Aqara leak - kitchen
          - entity: sensor.leaksensortoilet_battery
            name: Aqara leak - toilet
          - entity: sensor.livingroombalconywindow_battery
            name: Aqara window balcony - livingroom
          - entity: sensor.livingroomwindow_battery
            name: Aqara window - livingroom
          - entity: sensor.wardobewindow_battery
            name: Aqara window - wardobe
          - entity: sensor.maindoor_battery
            name: Aqara door - anteroom
          - entity: sensor.toiletdoor_battery
            name: Aqara door - toilet
          - entity: sensor.ringvibration_battery
            name: Aqara Doorbell - anteroom
          - entity: sensor.thermochildroom_battery
            name: Eurotronic thermo - child room
          - entity: sensor.thermolivingroom_battery
            name: Eurotronic thermo - livingroom

        show_header_toggle: false
        type: entities

    icon: 'mdi:battery'
    panel: false
    path: Battery
    theme: default_view
    title: Battery