kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-grafana
  labels:
    type: host
spec:
  # set to empty to disable dynamic provisioning using StorageClass
  storageClassName: "config-grafana"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
