apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-grafana
  labels: 
    app: influxdb-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-grafana
  template:
    metadata:
      labels:
        app: influxdb-grafana
    spec:
      containers:
      - name: influxdb-grafana
        image: philhawthorne/docker-influxdb-grafana:latest
        ports:
        - containerPort: 3003
        readinessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: config-grafana
        - mountPath: /var/lib/influxdb
          name: config-influxdb
      volumes:
      - name: config-grafana
        persistentVolumeClaim:
          claimName: config-grafana
      - name: config-influxdb
        persistentVolumeClaim:
          claimName: config-influxdb