apiVersion: v1
kind: Service
metadata:
  name: esphome
spec:
  selector:
    app: esphome
  ports:
    - name: esphome-http
      protocol: TCP
      port: 6052
      targetPort: 6052
  externalIPs:
    - 192.168.1.2
  type: ClusterIP
