apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels: 
    app: homeassistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:0.111.4
        ports:
        - containerPort: 8123
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - mountPath: /config
          name: homeassistant
      volumes:
      - name: homeassistant
        persistentVolumeClaim:
          claimName: homeassistant
