apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - name: homeasssitant
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: homekit
      protocol: TCP
      port: 51827
      targetPort: 51827
  externalIPs:
    - 192.168.1.2
  type: ClusterIP
