- alias: Switch Light Toilet 1
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchtoilet1_click
    to: right
  action:
    entity_id: light.osrambulbsgrouptoilet
    service: light.toggle
  # action:
  # - service: tts.google_cloud_say
  #   data:
  #       entity_id: media_player.echo
  #       message: "Cześć Andrzej, działa wszystko wyśmienicie"

- alias: Switch Light Toilet 2
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchtoilet1_click
    to: left
  action:
    entity_id: light.ikeabulbsgrouptoiletmirror
    service: light.toggle

- alias: Turn Off Light Toilet 1 & 2
  trigger:  
    platform: state
    entity_id: sensor.aqaraswitchtoilet1_click
    to: right_double
  action:
    entity_id:   
      - light.ikeabulbsgrouptoiletmirror
      - light.osrambulbsgrouptoilet
    service: light.turn_off       

- alias: Turn Off Light 1,2,3
  trigger:  
    platform: state
    entity_id: sensor.aqaraswitchlivingroom1_click
    to: right_double
  action:
    entity_id: 
      - switch.light1_relay
      - switch.light2_relay
      - switch.light3_relay
    service: switch.turn_off

- alias: Switch Light 1
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchlivingroom1_click
    to: right
  action:
    entity_id: switch.light1_relay
    service: switch.toggle

- alias: Switch Light 2
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchlivingroom1_click
    to: left
  action:
    entity_id: switch.light2_relay
    service: switch.toggle

- alias: Switch Light 3
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchlivingroom2_click
    to: right
  action:
    entity_id: switch.light3_relay
    service: switch.toggle

- alias: Switch Light Anteroom 1
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchanteroom1_click
    to: right
  action:
    entity_id: light.ikeabulbsgroupanteroom1
    service: light.toggle

- alias: Switch Light Anteroom 2
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchanteroom1_click
    to: left
  action:
    entity_id: light.ikeabulbsgroupanteroom2
    service: light.toggle

- alias: Lamp Table Kitchen
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchkitchen1_click
    to: single
  action:
    entity_id: light.ikeabulbsgroupkitchen
    service: light.toggle 

# Manual turnoff lights
- alias: Switch Off Light in the Kitchen & Anteroom
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchkitchen1_click
    to: double
  action:
    entity_id: 
      - light.ikeabulbsgroupkitchen
      - light.lamp_kitchen
      - light.ikeabulbsgroupanteroom1
      - light.ikeabulbsgroupanteroom2
    service: light.turn_off     

# Auto turnoff lights
- alias: Switch Off Light in the Kitchen & Anteroom 2
  trigger: 
    platform: state
    entity_id: 
      - binary_sensor.motionkitchen_occupancy
    from: "on"
    to: "off"
    for:
      minutes: 2
  action:
    entity_id: 
      - light.ikeabulbsgroupanteroom1
      - light.ikeabulbsgroupanteroom2
    service: light.turn_off     

- alias: Lamp Kitchen
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchkitchen2_click
    to: single
  action:
    entity_id: light.lamp_kitchen
    service: light.toggle  

- alias: Enable Washer
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchlivingroom2_click
    to: left
  action:
    entity_id: switch.washermachine_relay
    service: switch.turn_on

- alias: Disable Washer
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchlivingroom2_click
    to: left_double
  action:
    entity_id: switch.washermachine_relay
    service: switch.turn_off

# Switches Childroom 1
- alias: Lamp Childroom
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchchildroom_click
    to: single
  action:
    - service: light.toggle
      entity_id: light.aqaralampchildroom_light
    - service: input_select.select_option
      data:
        entity_id: input_select.light_childroom
        option: "OFF"

- alias: Lamp Childroom 2
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchchildroom2_click
    to: single
  action:
    - service: light.toggle
      entity_id: light.aqaralampchildroom_light
    - service: input_select.select_option
      data:
        entity_id: input_select.light_childroom
        option: "OFF"

# Switches Childroom 2
- alias: Light Childroom
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchwardrobe_click
    to: single
  action:
    - service: light.toggle
      entity_id: light.ikeabulbsgroupwardobe
    - service: input_select.select_option
      data:
        entity_id: input_select.light_childroom2
        option: "OFF"

- alias: Light Childroom 2
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchchildroom3_click
    to: single
  action:
    - service: light.toggle
      entity_id: light.ikeabulbsgroupwardobe
    - service: input_select.select_option
      data:
        entity_id: input_select.light_childroom2
        option: "OFF"

# Autooff all double click
- alias: Lamp Childroom Off All
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchwardrobe_click
    to: double
  action:
    - service: light.turn_off
      entity_id:
        - light.aqaralampchildroom_light
        - light.ikeabulbsgroupwardobe
    - service: input_select.select_option
      data:
        entity_id: 
          - input_select.light_childroom
          - input_select.light_childroom2
        option: "OFF"

- alias: Lamp Childroom Off All 2
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchchildroom_click
    to: double
  action:
    - service: light.turn_off
      entity_id:
        - light.aqaralampchildroom_light
        - light.ikeabulbsgroupwardobe
    - service: input_select.select_option
      data:
        entity_id: 
          - input_select.light_childroom
          - input_select.light_childroom2
        option: "OFF"

- alias: Lamp Childroom Off All 3
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchchildroom2_click
    to: double
  action:
    - service: light.turn_off
      entity_id:
        - light.aqaralampchildroom_light
        - light.ikeabulbsgroupwardobe
    - service: input_select.select_option
      data:
        entity_id: 
          - input_select.light_childroom
          - input_select.light_childroom2
        option: "OFF"

- alias: Lamp Childroom Off All 4
  trigger:
    platform: state
    entity_id: sensor.aqaraswitchchildroom3_click
    to: double
  action:
    - service: light.turn_off
      entity_id:
        - light.aqaralampchildroom_light
        - light.ikeabulbsgroupwardobe
    - service: input_select.select_option
      data:
        entity_id: 
          - input_select.light_childroom
          - input_select.light_childroom2
        option: "OFF"

# Auto off child room 1
- alias: Turn On Light Childroom if auto light off
  trigger: 
    platform: state
    entity_id: binary_sensor.motionchildroom_occupancy
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: input_select.light_childroom
      state: "ON"
    - condition: time
      after: '05:00:00'
      before: '23:00:00'
  action: 
    - service: light.turn_on
      entity_id: light.aqaralampchildroom_light

- alias: Turn Off Light Childroom 10 No Occupancy
  trigger: 
    platform: state
    entity_id: binary_sensor.motionchildroom_occupancy
    from: "on"
    to: "off"
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: light.aqaralampchildroom_light
      state: "on"
  action: 
    - service: light.turn_off
      entity_id:
        - light.aqaralampchildroom_light
    - service: input_select.select_option
      data:
        entity_id: input_select.light_childroom
        option: "ON"

# Auto off child room 2
- alias: Turn On Light Childroom if auto light off
  trigger: 
    platform: state
    entity_id: binary_sensor.motionchildroom2_occupancy
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: input_select.light_childroom2
      state: "ON"
    - condition: time
      after: '05:00:00'
      before: '23:00:00'
  action: 
    - service: light.turn_on
      entity_id: light.ikeabulbsgroupwardobe

- alias: Turn Off Light Childroom 10 No Occupancy
  trigger: 
    platform: state
    entity_id: binary_sensor.motionchildroom2_occupancy
    from: "on"
    to: "off"
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: light.ikeabulbsgroupwardobe
      state: "on"
  action: 
    - service: light.turn_off
      entity_id:
        - light.ikeabulbsgroupwardobe
    - service: input_select.select_option
      data:
        entity_id: input_select.light_childroom2
        option: "ON"        

# Away Mode In Weekdays 
- alias: Set Away Mode 
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on' 
    - condition: state
      entity_id: device_tracker.iphone_luci_andrzej
      state: "not_home"
    - condition: state
      entity_id: device_tracker.xiaomired_luci_ania
      state: "not_home"  
  action:
    - service: climate.turn_off
      data:
        entity_id: 
          - climate.thermochildroom_climate
          - climate.thermolivingroom_climate

# Away Mode 23 In Weekdays (person in home)
- alias: Set Home Mode 
  trigger:
    platform: time
    at: "07:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: state
        entity_id: input_select.thermo_season
        state: "ON"
      - condition: or
        conditions:
          - condition: state
            entity_id: device_tracker.iphone_luci_andrzej
            state: "home"
          - condition: state
            entity_id: device_tracker.xiaomired_luci_ania
            state: "home"  
  action:
    - service: climate.set_temperature
      data:
        entity_id: 
          - climate.thermochildroom_climate
          - climate.thermolivingroom_climate
        temperature: 23
        hvac_mode: auto          

# Set 23 Time 16:00 In Weekdays
- alias: Set Auto 23 Day Mode 
  trigger:
    platform: time
    at: "15:30:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: state
      entity_id: input_select.thermo_season
      state: "ON"
  action:
    - service: climate.set_temperature
      data:
        entity_id: 
          - climate.thermochildroom_climate
          - climate.thermolivingroom_climate
        temperature: 23
        hvac_mode: auto            

# Night Mode Good Sleep
- alias: Set Auto 20 Night Mode 
  trigger:
    platform: time
    at: "01:30:00"
  condition:
    - condition: state
      entity_id: input_select.thermo_season
      state: "ON"
  action:
    - service: climate.set_temperature
      data:
        entity_id: 
          - climate.thermochildroom_climate
          - climate.thermolivingroom_climate
        temperature: 20
        hvac_mode: auto        

# Set 23 Time 7:00 in Weekends      
- alias: Set Auto 23 Day Mode Weekends
  trigger:
    platform: time
    at: "07:00:00"
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    - condition: state
      entity_id: input_select.thermo_season
      state: "ON"
  action:
    - service: climate.set_temperature
      data:
        entity_id: 
          - climate.thermochildroom_climate
          - climate.thermolivingroom_climate
        temperature: 23
        hvac_mode: auto          

# Auto Light in Kithen Sunset
- alias: Turn on Light in Kitchen
  trigger: 
    platform: state
    entity_id: binary_sensor.motionkitchen2_occupancy
    from: "off"
    to: "on"
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:15:00"
  action: 
    service: light.turn_on
    data:
      brightness: 255
      entity_id:
        - light.lamp_kitchen

# Auto Light Off Kithen Sunset
- alias: Turn off Light in Kitchen
  trigger: 
    platform: state
    entity_id: binary_sensor.motionkitchen2_occupancy
    from: "on"
    to: "off"
    for:
      minutes: 3
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:15:00"
  action: 
    entity_id: light.lamp_kitchen
    service: light.turn_off 

# Auto Light in Kithen Day
- alias: Turn on Light in Kitchen Day
  trigger: 
    platform: state
    entity_id: binary_sensor.motionkitchen2_occupancy
    from: "off"
    to: "on"
  condition:
    - condition: sun
      before: sunrise
    - condition: time
      after: '05:30:00'
  action: 
    service: light.turn_on
    data:
      brightness: 254
      entity_id:
        - light.lamp_kitchen

# Auto Light Off Kithen Day 2
- alias: Turn off Light in Kitchen Day
  trigger: 
    platform: state
    entity_id: binary_sensor.motionkitchen2_occupancy
    from: "on"
    to: "off"
    for:
      minutes: 10
  action: 
    entity_id: light.lamp_kitchen
    service: light.turn_off     
    
# Auto Light in Toilet In Day Mode
- alias: Turn On Light In Toilet
  trigger: 
    platform: state
    entity_id: binary_sensor.motiontoilet_occupancy
    from: "off"
    to: "on"
  condition:
    - condition: time
      after: '05:00:00'
      before: '23:45:00'
    - condition: state
      entity_id: binary_sensor.toiletdoor_contact
      state:  "on"     
  action: 
    service: light.turn_on 
    data:
      transition: 0
      brightness: 254
      entity_id:
        - light.osrambulbsgrouptoilet      

# Auto Light in Toilet In Night Mode
- alias: Turn On Light In Toilet 20%
  trigger: 
    platform: state
    entity_id: binary_sensor.motiontoilet_occupancy
    from: "off"
    to: "on"
  condition:
    - condition: time
      after: '23:45:00'
      before: '05:00:00'   
    - condition: state
      entity_id: binary_sensor.toiletdoor_contact
      state:  "on"  
  action: 
    service: light.turn_on          
    data:
      transition: 5
      brightness: 20
      entity_id:
        - light.osrambulbsgrouptoilet

# Auto Light in Toilet In Night Mode Condition
- alias: Turn On Light In Toilet 20% Condition
  trigger: 
    platform: state
    entity_id: binary_sensor.motiontoilet_occupancy
    from: "off"
    to: "on"
  condition:
    - condition: time
      after: '23:45:00'
      before: '05:00:00'   
    - condition: state
      entity_id: binary_sensor.toiletdoor_contact
      state:  "on"  
    - condition: state
      entity_id: light.yamaha
      state: "on"
  action: 
    service: light.turn_on          
    data:
      transition: 0
      brightness: 254
      entity_id:
        - light.osrambulbsgrouptoilet

# Auto Light Off In Toilet 10 minutes no occupancy
- alias: Turn Off Light Toilet 10 No Occupancy
  trigger: 
    platform: state
    entity_id: binary_sensor.motiontoilet_occupancy
    from: "on"
    to: "off"
    for:
      minutes: 10
  action: 
    - service: light.turn_off
      entity_id:
        - light.osrambulbsgrouptoilet  
        - light.ikeabulbsgrouptoiletmirror

# Auto Turn on Light in Anteroom Enter Home
- alias: Turn on Light in Anteroom Enter Home
  trigger: 
    platform: state
    entity_id: binary_sensor.maindoor_contact
    from: "off"
    to: "on"
  condition:
      - condition: sun
        after: sunset
        after_offset: "-00:15:00"
      - condition: state
        entity_id: binary_sensor.motionkitchen_occupancy
        state: "off"   
  action: 
    service: light.turn_on
    data:
      brightness: 254
      entity_id:
        - light.ikeabulbsgroupanteroom1 

- alias: "Ring Auto Off"
  trigger:
    platform: state
    entity_id: sensor.ringvibration_action
    to: vibration 
    for: 
      minutes: 2
  action:
    service: mqtt.publish
    data:
      topic: "zigbee2mqtt/RingVibration/action"
      payload: "unknown"

- alias: 'Set theme at startup'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: "Google Dark Theme Oled"

# Amazon Echo
- alias: "Sound Low Alexa Echo"
  trigger:
    platform: time
    at: "21:00:00"   
  action:
    - service: media_player.volume_set
      data:
          entity_id: media_player.echo
          volume_level: 0.1

- alias: "Sound Up Alexa Echo"
  trigger:
    platform: time
    at: "07:00:00"   
  action:
    - service: media_player.volume_set
      data:
          entity_id: media_player.echo
          volume_level: 0.5