- alias: Auto Blinds Up Down
  trigger: 
    - platform: time
      at: "22:30:00"
  action:
    - service: cover.close_cover
      entity_id: 
      - cover.covers_all
    - service: cover.open_cover
      entity_id: 
      - cover.blindsofficewindow1
      - cover.blindsofficewindow2
    - service:  notify.mobile_app_iphone
      data:
        title: "Blinds"
        message: "All Blinds Close"
        data:
          push:
            sound: default

- alias: Auto Blinds Up Down - Sunny Day
  trigger:
    - platform: time_pattern
      hours: "/1"
    - platform: numeric_state
      entity_id: weather.home
      attribute: temperature
      above: 25
    - platform: state
      entity_id: binary_sensor.burze_dzis_net_ostrzezenie_upal
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '08:00:00'
        before: '15:00:00'
      - condition: numeric_state
        entity_id: weather.home
        attribute: temperature
        above: 25
      - condition: numeric_state
        entity_id: weather.home
        attribute: cloud_coverage
        below: 80
      - condition: state
        entity_id: cover.covers_all
        state: 'open'
      - condition: state
        entity_id: input_select.covers_sun
        state: "OFF"
  action:
    - service: cover.close_cover
      entity_id: 
      - cover.covers_all
    - service: sonos.snapshot
      entity_id: all
    - service: notify.sonos
      data:
        message: "Robi się upalnie i słonecznie, zasłaniam wszystkie rolety w mieszkaniu"
    - delay: 00:00:05
    - service: sonos.restore
      entity_id: all
    - service:  notify.mobile_app_iphone
      data:
        title: "Blinds"
        message: "All Blinds Close"
        data:
          push:
          sound: default

- alias: Reset Condition Blinds (Turn On Automation)
  trigger: 
    - platform: time
      at: "07:30:00"
  action:
    - service: input_select.select_option
      data:
        entity_id: 
          - input_select.covers_sun
        option: "OFF"

- alias: Auto Blinds Up Morning - Sunset
  trigger: 
    - platform: time
      at: "07:00:00"
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
  action:
    - service: cover.open_cover
      entity_id: 
      - cover.covers_all
    - service:  notify.mobile_app_iphone
      data:
        title: "Blinds"
        message: "All Blinds Open"
        data:
          push:
            sound: default