- alias: Auto Blinds Up Down
  trigger: 
    - platform: time
      at: "22:30:00"
  action:
    - service: cover.close_cover
      entity_id: 
      - cover.covers_all

- alias: Auto Blinds Up Down - Sunny
  trigger:
    - platform: time_pattern
      hours: "/1"
    - platform: numeric_state
      entity_id: weather.home
      attribute: temperature
      above: 25
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: time
        after: '08:00:00'
        before: '15:00:00'
      - condition: state
        entity_id: cover.covers_all
        state: 'open'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.burze_dzis_net_ostrzezenie_upal
            state: 'on'
  action:
    - service: cover.close_cover
      entity_id: 
      - cover.covers_all
    - service: sonos.snapshot
      entity_id: all
    - service: notify.sonos
      data:
        message: "Robi się upalnie i słonecznie, zasłaniam wszystkie rolety w mieszkaniu"
    - delay: 00:00:05
    - service: sonos.restore
      entity_id: all

- alias: Auto Blinds Up Sunrise
  trigger: 
    - platform: time
      at: "07:00:00"
  action:
    - service: cover.open_cover
      entity_id: 
      - cover.covers_all
