# - alias: Auto Blinds Up
#   trigger: 
#     - platform: state
#       entity_id: 
#         - weather.home
#       to: 
#       - "cloudy"
#       - "rainy"
#     - platform: sun
#       event: sunset
#       offset: "-02:00:00"
#   condition:
#     - condition: time
#       after: '16:00:00'
#       before: '19:30:00'
#   action:
#     - service: script.turn_on
#       entity_id: 
#       - script.covers_open
