- alias: "Ring Auto Off"
  trigger:
    platform: state
    entity_id: sensor.ringvibration_action
    to: vibration 
    for: 
      minutes: 2
  action:
    service: mqtt.publish
    data:
      topic: "zigbee2mqtt/RingVibration/action"
      payload: "unknown"