- alias: "Turn On Living Room TV"
  trigger:
    - platform: webostv.turn_on
      entity_id: media_player.tv
  action:
    - service: remote.send_command
      entity_id: 'remote.xiaomi_miio'
      data:
        command:
        - raw:Z6VHACsCAACjBgAAyggAAI4RAAA9IwAACJ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAAABAAAAAAEBAQABAQEBBQJAA='  
