- alias: xyz
  trigger:
    - platform: state
      entity_id: binary_sensor.maindoor_contact
      from: "off"
      to: "on"
  action:
    - service: notify.mobile_app_iphone
      data:
        message: Something happened at home!
        data:
          push:
            category: map
          action_data:
            latitude: "{{ state_attr('device_tracker.redmi_note_4', 'latitude') }}"
            longitude: "{{ state_attr('device_tracker.redmi_note_4', 'longitude') }}"