- alias: 'Set theme at startup'
  id: set_theme_at_startup
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: "Google Dark Theme Oled"
