- alias: Vacum Start Actions iOS 
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: STOP
  action:
    service: script.turn_on
    target:
      entity_id: script.stop_clean_home

- alias: Vacum Stop Actions iOS 
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: START_HOME
  action:
    service: script.turn_on
    target:
      entity_id: script.clean_home

- alias: Vacum Stop Actions iOS 
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: START_WHITE_FLOOR
  action:
    service: script.turn_on
    target:
      entity_id: script.clean_white_floor
