- platform: template
  sensors:
    vacuum_cleaning:
      friendly_name: "Vacuum Cleaning"
      value_template: >-
        {{ is_state('vacuum.john', 'cleaning') }}

# Lock
- platform: template
  sensors:
    lock:
      value_template: >-
        {{ is_state("lock.maindoorlock", "unlocked") }}
      icon_template: >-
        {% if is_state("binary_sensor.lock", "on") %}
          mdi:lockopen
        {% else %}
          mdi:lock
        {% endif %}
