# Binary sensor
- platform: template
  sensors:
    doorbell:
      friendly_name: "Doorbell"
      delay_off:
        minutes: 2
      value_template: >-
        {{ is_state('sensor.ringvibration_action', 'vibration') }}
      icon_template: >-
        {% if is_state("binary_sensor.doorbell", "on") %}
          mdi:bell-ring
        {% else %}
          mdi:bell
        {% endif %}

- platform: template
  sensors:
    vacuum_cleaning:
      friendly_name: "Vacuum Cleaning"
      value_template: >-
        {{ is_state('vacuum.john', 'cleaning') }}

# Lock
- platform: template
  sensors:
    lock:
      value_template: >-
        {{ is_state("lock.maindoorlock", "unlocked") }}
      icon_template: >-
        {% if is_state("binary_sensor.lock", "on") %}
          mdi:lockopen
        {% else %}
          mdi:lock
        {% endif %}
