platform: xiaomi_cloud_map_extractor
host: !secret xiaomi_vacuum_host
token: !secret xiaomi_vacuum_token
username: !secret xiaomi_cloud_username
password: !secret xiaomi_cloud_password
country: "de"
colors:
  color_path: [255, 255, 255]
draw: ['all']
map_transformation:
  scale: 3
  rotate: 90
  trim:
    top: 10
    bottom: 10
    left: 10
    right: 10
auto_update: true
store_map_raw: true
store_map_image: true
scan_interval:
  seconds: 400
attributes:
  - calibration_points
colors:
  color_map_inside: [29, 29, 28]
  color_map_outside: [29, 29, 28]
  color_map_wall: [100, 196, 254]
  color_map_wall_v2: [23, 23, 23]
  color_grey_wall: [23, 23, 23]
  color_ignored_obstacle: [0, 0, 0, 127]
  color_ignored_obstacle_with_photo: [0, 0, 0, 127]
  color_obstacle: [0, 0, 0, 127]
  color_obstacle_with_photo: [0, 0, 0, 127]
  color_path: [147, 194, 238]
  color_goto_path: [0, 255, 0]
  color_predicted_path: [255, 255, 0, 0]
  color_cleaned_area: [127, 127, 127, 127]
  color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
  color_zones_outline: [0xAD, 0xD8, 0xFF]
  color_virtual_walls: [255, 0, 0]
  color_new_discovered_area: [64, 64, 64]
  color_no_go_zones: [255, 33, 55, 127]
  color_no_go_zones_outline: [255, 0, 0]
  color_no_mop_zones: [163, 130, 211, 127]
  color_no_mop_zones_outline: [163, 130, 211]
  color_charger: [0x66, 0xfe, 0xda, 0x7f]
  color_robo: [75, 235, 149]
  color_room_names: [0, 0, 0]
  color_unknown: [0, 0, 0]
  color_scan: [0xDF, 0xDF, 0xDF]
room_colors:
  16: [0, 140, 236]   # office
  17: [0, 140, 236] # kitchen
  18: [0, 140, 236] # child room
  19: [0, 140, 236] # ante room
  21: [0, 140, 236]   # living room
  22: [0, 140, 236]  # toilet 
  # 16: [1, 128, 181]   # office
  # 17: [179, 247, 154] # kitchen
  # 18: [253, 154, 251] # child room
  # 19: [148, 166, 180] # ante room
  # 21: [61, 93, 154]   # living room
  # 22: [255, 196, 56]  # toilet
draw:
  - charger
  - cleaned_area
  - goto_path
  - ignored_obstacles
  - ignored_obstacles_with_photo
  - no_go_zones
  - no_mopping_zones
  - obstacles
  - obstacles_with_photo
  - path
  - predicted_path
  - room_names
  - vacuum_position
  - virtual_walls
  - zones
sizes:
  charger_radius: 0
  vacuum_radius: 0
  obstacle_radius: 0
  ignored_obstacle_radius: 0
  obstacle_with_photo_radius: 0
  ignored_obstacle_with_photo_radius: 0
attributes:
  - calibration_points
  - charger
  - cleaned_rooms
  - country
  - goto
  - goto_path
  - goto_predicted_path
  - image
  - is_empty
  - map_name
  - no_go_areas
  - no_mopping_areas
  - obstacles
  - ignored_obstacles
  - obstacles_with_photo
  - ignored_obstacles_with_photo
  - path
  - room_numbers
  - rooms
  - vacuum_position
  - vacuum_room
  - vacuum_room_name
  - walls
  - zones

