person.ania:
  entity_picture: /local/ania.jpg
person.andrzej:
  entity_picture: /local/andrzej.jpg
device_tracker.iphone_luci_andrzej:
  entity_picture: /local/andrzej.jpg
device_tracker.samsung_a36:
  entity_picture: /local/ania.jpg
sensor.home_ania:
  entity_picture: /local/ania.jpg
sensor.home_andrzej:
  entity_picture: /local/andrzej.jpg
sensor.sui_wallet:
  icon: mdi:wallet
  friendly_name: "SUI Portfolio"
