port: 21065
name: bridge-homekit
filter:
  include_entities:
    - light.aqaralampchildroom_light
    - light.ikeabulblamp_light
    - switch.hdmi2
    - switch.washermachine
    - switch.radio
    - light.group_livingroom_1
    - light.lightlivingroomleftright_l1
    - light.lightlivingroomleftright_l2
    - switch.yamaha
    - switch.blitzlivingroomcommod
    - switch.blitzlivingroomrtv
    - switch.blitzlivingroomglasscase
    - sensor.air_purifier_humidity
    - sensor.air_purifier_temperature
    - light.group_1_toilet_1
    - light.group_5_toilet_2
    - light.group_6_wardobe_1
    - sensor.i_lo_siemianowice_slaskie_pm2_5
    - binary_sensor.toiletdoor_contact
    - binary_sensor.livingroomwindow_contact
    - binary_sensor.maindoor_contact
    - binary_sensor.livingroombalconywindow_contact
    - binary_sensor.childroomwindow_contact
    - binary_sensor.kitchenwindow_contact
    - binary_sensor.wardobewindow_contact
    - binary_sensor.leaksensortoilet_water_leak
    - binary_sensor.motionkitchen_occupancy
    - binary_sensor.motionkitchen2_occupancy
    - binary_sensor.motiontoilet_occupancy
    - binary_sensor.motionchildroom_occupancy
    - binary_sensor.motionchildroom2_occupancy
    - light.lamp_kitchen
    - light.group_2_anteroom_1
    - light.group_3_anteroom_2
    - light.group_4_office_1
    - light.philipsledoffice
    - light.philipsledofficeleft
    - light.philipsledofficeright
    - device_tracker.iphone
    - device_tracker.samsung
    - scene.good_night
    - climate.thermochildroom_climate
    - climate.thermolivingroom_climate
    - climate.thermokitchen_climate
    - media_player.tv
    - fan.air_purifier
    - lock.maindoorlock
    - cover.covers_living_room
    - cover.covers_office_room
    - cover.blindschildroomwindow1
    - cover.blindskitchenwindow1
    - script.covers_close
    - script.covers_open
