- port: 21065
  name: bridge-homekit
  filter:
    include_entities:
      - script.good_night
      - binary_sensor.presense_sensor_toilet_up
      - sensor.presense_sensor_toilet_up_illuminance
      - fan.air_purifier
    include_entity_globs:
      - light.*
    exclude_entities:
      - light.u6_pro_led
      - light.home_assistant_voice_093e77_led_ring
      - light.u7_pro_xg_led
