- platform: mqtt
  schema: json
  name: OsramBulbsGroupToilet
  command_topic: "zigbee2mqtt/group_1_toilet_1/set"
  state_topic: "zigbee2mqtt/group_1_toilet_1"
  brightness: true

- platform: mqtt
  schema: json
  name: IkeaBulbsGroupAnteroom1
  command_topic: "zigbee2mqtt/group_2_anteroom_1/set"
  state_topic: "zigbee2mqtt/group_2_anteroom_1" 
  brightness: true

- platform: mqtt
  schema: json
  name: IkeaBulbsGroupAnteroom2
  command_topic: "zigbee2mqtt/group_3_anteroom_2/set"
  state_topic: "zigbee2mqtt/group_3_anteroom_2" 
  brightness: true

- platform: mqtt
  schema: json
  name: IkeaBulbsGroupKitchen
  command_topic: "zigbee2mqtt/group_4_kitchen_1/set"
  state_topic: "zigbee2mqtt/group_4_kitchen_1"
  brightness: true  

- platform: mqtt
  schema: json
  name: IkeaBulbsGroupToiletMirror
  command_topic: "zigbee2mqtt/group_5_toilet_2/set"
  state_topic: "zigbee2mqtt/group_5_toilet_2"
  brightness: true     

- platform: mqtt
  schema: json
  name: IkeaBulbsGroupWardobe
  command_topic: "zigbee2mqtt/group_6_wardobe_1/set"
  state_topic: "zigbee2mqtt/group_6_wardobe_1"
  brightness: true 

# Single
- platform: "mqtt"
  state_topic: "zigbee2mqtt/IkeaBulbToiletMirror"
  availability_topic: "zigbee2mqtt/bridge/state"
  schema: "json"
  command_topic: "zigbee2mqtt/IkeaBulbToiletMirror/set"  
  brightness: true
  color_temp: false
  rgb: false
