db_url: postgresql://postgres:k2JIGuP3KJ@postgresql.postgresql.svc.cluster.local/postgres
auto_purge: true
exclude:
  domains:
    - automation
    - updater
  entity_globs:
    - sensor.weather_*
  entities:
    - sun.sun 
    - sensor.last_boot
    - sensor.date
  event_types:
    - call_service
