db_url: postgresql://hass:7uy8ot5ZuCrex5pwwr1YWtHEZ0HvOMqLJTbuf3ThsE5KWGfmAvLLJSNvw2JMPCJH@postgres-hass.postgresql.svc.cluster.local/hass
auto_purge: true
exclude:
  domains:
    - automation
    - updater
  entity_globs:
    - sensor.weather_*
  entities:
    - sun.sun 
    - sensor.last_boot
    - sensor.date
  event_types:
    - call_service
