- platform: xiaomi_miio
  host: 192.168.1.3    
  token: e97db4b3d0ffd51e6eda924b270fb2e4
  slot: 1
  timeout: 30
  hidden: false
  commands:
    yamaha:
      command:
        - raw:Z6VDADcCAAB3BgAAaBEAAAwjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjABAAEBAQEAAQABAAAAAAEBAAABAAAAAAABAQABAQEAAA