- id: '1577046394155'
  name: Good Evening
  entities:
    switch.blitzlivingroomrtv:
      state: 'on'
    switch.blitzlivingroomglasscase:
      state: 'on'
    switch.blitzlivingroomcommod:
      state: 'on'
    light.aqaralampchildroom_light:
      state: 'on'
    light.ikeabulbsgroupanteroom1:
      state: 'on'  
    switch.air_purifier_led:
      state: 'on'
    switch.radio:
      state: 'on' 

- id: '1577085914679'
  name: Good Night
  entities:
    switch.light2_relay:
      state: 'off'
    switch.light1_relay:
      state: 'off'
    switch.light3_relay:
      state: 'off'
    switch.air_purifier_led:
      state: 'off'
    light.aqaralampchildroom_light:
      state: 'off'
    light.ikeabulblamp_light:
      state: 'off'
    switch.yamaha:
      state: 'off'  
    switch.nc:
      state: 'off'
    switch.blitzlivingroomcommod:
      state: 'off'
    switch.blitzlivingroomrtv:
      state: 'off'
    switch.blitzlivingroomglasscase:
      state: 'off'
    media_player.tv:
      state: 'off'
    light.ikeabulbsgroupkitchen:  
      state: 'off'
    light.lamp_kitchen:
      state: 'off'
    light.ikeabulbsgroupanteroom2:
      state: 'off'
    light.osrambulbsgrouptoilet:
      state: 'off'       
    light.ikeabulbsgrouptoiletmirror:
      state: 'off'   
    light.ikeabulbsgroupanteroom1:
      state: 'off' 
    light.ikeabulbsgroupwardobe:
      state: 'off' 
    light.philipsledoffice:
      state: 'off'
    light.philipsledofficeleft:
      state: 'off'
    light.philipsledofficeright:
      state: 'off'
    media_player.echo:
      state: standby
    media_player.appletv:
      state: paused

- id: '1577085924679'
  name: Good Morning
  entities:
    switch.yamaha:
      state: 'on'   
    media_player.tv:
      state: 'on'
    switch.nc:
      state: 'on'        
    switch.hdmi1: 
      state: 'on'
    switch.air_purifier_led:
      state: 'on'

- id: 'cinema'
  name: Cinema
  entities:
    # switch.yamaha:
    #   state: 'on'   
    # media_player.tv:
    #   state: 'on'      
    # switch.hdmi2: 
    #   state: 'on' 
    script.appletv_tv:
      state: 'on'

