- id: '1577046394155'
  name: Good Evening
  entities:
    switch.blitzlivingroomrtv:
      state: 'on'
    switch.blitzlivingroomglasscase:
      state: 'on'
    switch.blitzlivingroomcommod:
      state: 'on'
    light.aqaralampchildroom_light:
      state: 'on'
    light.group_2_anteroom_1:
      state: 'on'  
    switch.air_purifier_led:
      state: 'on'
    switch.radio:
      state: 'on' 

- id: '1577085924679'
  name: Good Morning
  entities:
    switch.yamaha:
      state: 'on'   
    media_player.tv:
      state: 'on'
    switch.nc:
      state: 'on'        
    switch.hdmi1: 
      state: 'on'


