# Vacuum
clean_home:
  alias: Clean Home
  icon: mdi:home
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [16,17,18,19,20]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto
      
stop_clean_home:
  alias: Stop Clean Home
  icon: mdi:home
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:02
  - service: vacuum.return_to_base
    entity_id: vacuum.john

clean_dining_room:
  alias: Clean Dining Room
  icon: mdi:table-chair
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [16]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

clean_hall:
  alias: Clean Hall
  icon: mdi:coat-rack
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [17]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto
      repeats: 2

clean_living_room:
  alias: Clean Living Room
  icon: mdi:sofa
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [18]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

clean_kitchen:
  alias: Clean Kitchen
  icon: mdi:fridge-outline
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [19]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

clean_toilet_down:
  alias: Clean Toilet Down
  icon: mdi:toilet
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [20]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

# Good Night
good_night:
  alias: Good Night
  icon: mdi:bed-king
  sequence:
    # Turn off all lights
    - service: light.turn_off
      target:
        entity_id: all
    # Restore Unifi LEDs
    - service: light.turn_on
      target:
        entity_id:
          - light.u7_pro_xg_led
    # Pause Sonos
    - service: media_player.media_pause
      target:
        entity_id: 
          - media_player.office
          - media_player.toilet_up
          - media_player.living_room
    # Turn off Apple TV
    - service: media_player.turn_off
      target:
        entity_id:
          - media_player.tv_webos

work_mode:
  alias: Work Mode
  icon: mdi:desk-lamp
  sequence:
    - service: light.turn_on
      target:
        entity_id:
          - light.desk_led
          - light.office_lamp
      data:
        brightness_pct: 100
        