# RTV
miio_turn_on_tv:
  sequence:
  - data:
      command:
      - raw:Z6VHACsCAACjBgAAyggAAI4RAAA9IwAACJ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAAABAAAAAAEBAQABAQEBBQJAA=
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: TV 

miio_turn_on_nc:
  sequence:
  - data:
      command:
      - raw:Z6VLABUCAABIAgAAjQYAANIIAACnEQAAcyMAALyYAADoegEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFISEhAQEBASEBISEhIQEhAQEhAQEhAQEBIQEhIQEhISFhNXE1AQ==
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Canal+

miio_turn_on_yamaha_hdmi1:
  sequence:
  - data:
      command:
      - raw:Z6VLADQCAAB7BgAAtggAAGoRAAAIIwAAYJ8AAHB1AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ABAAEBAQEAAQABAAAAAAEBAQEAAAABAAAAAAEBAQAABQJGAkAA==
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: HDMI1  

miio_turn_on_yamaha_hdmi2:
  sequence:
  - data:
      command:
      - raw:Z6VLACMCAABFAgAAkQYAAM0IAACCEQAA8SIAAGCfAABwdQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFECAQICAgIBAgECAQEBAQIBAgECAQECAQIBAgECAgEBBgNXA1AA==
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: HDMI2  

miio_turn_on_yamaha_radio:
  sequence:
  - data:
      command:
      - raw:Z6VDADcCAAB3BgAAaBEAAAwjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjABAAEBAQEAAQABAAAAAAEBAAABAAAAAAABAQABAQEAAA
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Radio

miio_turn_on_yamaha:
  sequence:
  - data:
      command:
      - raw:Z6VHADYCAAB6BgAAtggAAG0RAAAIIwAAFJsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ABAQEBAQEAAQAAAAAAAAEAAQABAAEAAAEAAQABAAEBBQJAA=
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Yamaha

miio_turn_on_climate:
  sequence:
  - data:
      command:
      - raw:Z6VLABwCAABxAgAASAYAAIIIAABKEQAAACQAALyYAABEdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEBAQEBAQEhISEhISEhISEhAQEBASEBAQEhISEhASFhNXE1AQ==
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Climate-ON

miio_speed_climate:
  sequence:
  - data:
      command:
      - raw:Z6VLAEoCAABsBgAApwgAAG0RAAD8IwAAIJkAAKh0AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAQEBAQEBAQEBAAEAAAABAAABAAEBAQABBQJGAkAA==
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Climate-Speed

miio_osc_climate:
  sequence:
  - data:
      command:
      - raw:Z6VPABcCAAByAgAARwYAAH8IAABGEQAA6CMAALyYAABEdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEBAQEBAQEhISEhISEhIQEBAQEBASEBISEhISEhASFhNXE1cTUB
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Climate-OSC

# Vacuum
clean_home:
  alias: Clean Home
  icon: mdi:home
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [17,16,22,19,21,18]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto
      
stop_clean_home:
  alias: Stop Clean Home
  icon: mdi:home
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:02
  - service: vacuum.return_to_base
    entity_id: vacuum.john

clean_office:
  alias: Clean Office
  icon: mdi:desk
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [16]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: 105

clean_kitchen:
  alias: Clean Kitchen
  icon: mdi:table-chair
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [17]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto
      repeats: 2

clean_toilet:
  alias: Clean Toilet
  icon: mdi:toilet
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [22] 
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

clean_ante_room:
  alias: Clean Ante Room
  icon: mdi:town-hall
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [19]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

clean_living_room:
  alias: Clean Living Room
  icon: mdi:sofa
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [21]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

clean_child_room:
  alias: Clean Child Room
  icon: mdi:teddy-bear
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [18]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

clean_white_floor:
  alias: Clean White Floor
  icon: mdi:apps
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [17,16,19]
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.john
      fan_speed: Auto

# Blinds
covers_open:
  alias: All Covers Open
  icon: mdi:blinds-horizontal
  sequence:
  - service: cover.open_cover
    entity_id: 
    - cover.blindslivingroomwindow1
    - cover.blindslivingroomwindow2
    - cover.blindslivingroomwindow3
    - cover.blindschildroomwindow1
    - cover.blindsofficewindow1
    - cover.blindsofficewindow2
    - cover.blindskitchenwindow1

covers_close:
  alias: All Covers Close
  icon: mdi:blinds-horizontal
  sequence:
  - service: cover.close_cover
    entity_id: 
    - cover.blindslivingroomwindow1
    - cover.blindslivingroomwindow2
    - cover.blindslivingroomwindow3
    - cover.blindschildroomwindow1
    - cover.blindsofficewindow1
    - cover.blindsofficewindow2
    - cover.blindskitchenwindow1

# Work Day
work_day:
  alias: Work Day
  icon: mdi:blinds-horizontal
  sequence:
  - service: cover.close_cover
    entity_id: 
    - cover.blindslivingroomwindow1
    - cover.blindslivingroomwindow2
    - cover.blindslivingroomwindow3
    - cover.blindschildroomwindow1
    - cover.blindsofficewindow1
    - cover.blindsofficewindow2
    - cover.blindskitchenwindow1
  - service: light.turn_on
    entity_id: 
    - light.group_4_kitchen_1
    - light.philipsledoffice
    - light.philipsledofficeleft
    - light.philipsledofficeright
