miio_turn_on_tv:
  sequence:
  - data:
      command:
      - raw:Z6VHACsCAACjBgAAyggAAI4RAAA9IwAACJ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAAABAAAAAAEBAQABAQEBBQJAA=
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: TV 

miio_turn_on_nc:
  sequence:
  - data:
      command:
      - raw:Z6VLABUCAABIAgAAjQYAANIIAACnEQAAcyMAALyYAADoegEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFISEhAQEBASEBISEhIQEhAQEhAQEhAQEBIQEhIQEhISFhNXE1AQ==
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Canal+

miio_turn_on_yamaha_hdmi1:
  sequence:
  - data:
      command:
      - raw:Z6VLADQCAAB7BgAAtggAAGoRAAAIIwAAYJ8AAHB1AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ABAAEBAQEAAQABAAAAAAEBAQEAAAABAAAAAAEBAQAABQJGAkAA==
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: HDMI1  

miio_turn_on_yamaha_hdmi2:
  sequence:
  - data:
      command:
      - raw:Z6VLACMCAABFAgAAkQYAAM0IAACCEQAA8SIAAGCfAABwdQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFECAQICAgIBAgECAQEBAQIBAgECAQECAQIBAgECAgEBBgNXA1AA==
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: HDMI2  

miio_turn_on_yamaha_radio:
  sequence:
  - data:
      command:
      - raw:Z6VDADcCAAB3BgAAaBEAAAwjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjABAAEBAQEAAQABAAAAAAEBAAABAAAAAAABAQABAQEAAA
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Radio

miio_turn_on_yamaha:
  sequence:
  - data:
      command:
      - raw:Z6VHADYCAAB6BgAAtggAAG0RAAAIIwAAFJsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ABAQEBAQEAAQAAAAAAAAEAAQABAAEAAAEAAQABAAEBBQJAA=
    entity_id: remote.xiaomi_miio
    service: remote.send_command
  alias: Yamaha

play_spotify_1:
  sequence:
    - service: remote.send_command
      target:
        entity_id: remote.appletv
      data:
        delay_secs: 3.0
        command:
          - menu
          - menu
          - select
    - service: media_player.play_media
      target:
        entity_id: media_player.spotify
      data:
        media_content_id: "https://open.spotify.com/playlist/37i9dQZF1DWVoMrfBJGgYD?si=IOK4tvRISH6UnDwAC98d8Q"
        media_content_type: playlist

clean_home:
  alias: Clean Home
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [16,17,18,19,20,21]

clean_office:
  alias: Clean Office
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [16]

clean_kitchen:
  alias: Clean Kitchen
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [17]

clean_toilet:
  alias: Clean Toilet
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [18]

clean_ante_room:
  alias: Clean Ante Room
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [19]

clean_living_room:
  alias: Clean Living Room
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [20]

clean_child_room:
  alias: Clean Child Room
  sequence:
  - service: vacuum.stop
    entity_id: vacuum.john
  - delay: 00:00:01
  - service: vacuum.send_command
    data:
      entity_id: vacuum.john
      command: app_segment_clean
      params: [21]