- platform: google_cloud
  key_file: homeassistant-google.json
  language: pl-PL
  gender: male
  voice: pl-PL-Wavenet-E
  encoding: linear16
  speed: 1.0
  pitch: 0.0
  gain: 0.0
  profiles:
    - large-home-entertainment-class-device