name: tv
host: 192.168.1.6
turn_on_action:
  - service: remote.send_command
    entity_id: 'remote.xiaomi_miio'
    data:
      command:
      - raw:Z6VHACsCAACjBgAAyggAAI4RAAA9IwAACJ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAAABAAAAAAEBAQABAQEBBQJAA='  
customize:
  sources:
    - livetv
    - hdmi1
    - youtube
    - netflix  