- name: WPKiW
  latitude: !secret latitude_wpkiw
  longitude: !secret longitude_wpkiw
  radius: 250
  icon: mdi:account-hard-hat

- name: Yakudo
  latitude: !secret latitude_yakudo
  longitude: !secret longitude_yakudo
  radius: 250
  icon: mdi:account-hard-hat  

- name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 350
  icon: mdi:home