- name: WPKiW
  latitude: !secret latitude_wpkiw
  longitude: !secret longitude_wpkiw
  radius: 250
  icon: mdi:account-hard-hat

- name: eSky
  latitude: !secret latitude_esky
  longitude: !secret longitude_esky
  radius: 250
  icon: mdi:account-hard-hat  

- name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 350
  icon: mdi:home

- name: CityFit
  latitude: !secret latitude_city_fit
  longitude: !secret longitude_city_fit
  radius: 150
  icon: mdi:dumbbell

- name: Preschool
  latitude: !secret latitude_preschool
  longitude: !secret longitude_preschool
  radius: 150
  icon: mdi:teddy-bear