apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: smart-home
spec:
  selector:
    app: zigbee2mqtt
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: http-zigbee
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
