apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
  namespace: smart-home
  labels: 
    app: zigbee2mqtt
spec:
  serviceName: zigbee2mqtt
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:1.16.0
        # image: koenkk/zigbee2mqtt:1.15.0
        imagePullPolicy: Always
        env:
        - name: version
          value: 1.15.0.0
        ports:
        - containerPort: 1883
        volumeMounts:
        - mountPath: /app/data
          name: data-zigbee2mqtt
        - mountPath: /dev/ttyACM0
          name: zigbee-usb
        securityContext:
          privileged: true
      volumes:
      - name: data-zigbee2mqtt
        persistentVolumeClaim:
          claimName: data-zigbee2mqtt
      - name: zigbee-usb
        hostPath:
          path: /dev/ttyACM0
          type: CharDevice
