apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home
spec:
  selector:
    app: mosquitto
  ports:
    - name: mosquitto-mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mosquitto-emc2
      protocol: TCP
      port: 9001
      targetPort: 9001
  externalIPs:
    - 192.168.1.2
  type: ClusterIP
