apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home
  labels: 
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6.10
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - mountPath: /mosquitto/data
          name: config-data-mosquitto
      volumes:
      - name: config-data-mosquitto
        persistentVolumeClaim:
          claimName: config-data-mosquitto