kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-influxdb
  namespace: metrics
  labels:
    type: host
spec:
  # set to empty to disable dynamic provisioning using StorageClass
  storageClassName: "config-influxdb"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
