apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: metrics
spec:
  selector:
    app: influxdb
  ports:
    - name: influxdb-db
      protocol: TCP
      port: 8086
      targetPort: 8086
  externalIPs:
    - 192.168.1.2
  type: ClusterIP
