esphome:
  name: shelly2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret password

# Enable Home Assistant API
api:

ota:

logger:

i2c:
  sda: GPIO12
  scl: GPIO14

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
    name: "outlet Relay"
    on_press:
      then:
        - switch.toggle: outlet
  - platform: gpio
    pin:
      number: GPIO5
    name: "light1 Relay"
    on_press:
      then:
        - switch.toggle: light1

sensor:
  - platform: ntc
    sensor: shelly2_resistance_sensor
    id: shelly2_temperature
    name: "shelly2 Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    calibration:
      b_constant: 3350
      reference_temperature: 25°C
      reference_resistance: 10kOhm
  - platform: adc
    id: shelly2_source_sensor
    pin: A0
    update_interval: 10s
  - platform: resistance
    id: shelly2_resistance_sensor
    sensor: shelly2_source_sensor
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: ade7953
    voltage:
      name: "shelly2 Voltage"
    current_a: 
      name: "outlet Current"
    current_b:
      name: "light1 Current"
    active_power_a:
      name: "outlet Power"
    active_power_b:
      name: "light1 Power"
      filters:
      - multiply: -1.0
  - platform: uptime
    name: '${device_name} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574
  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 300s

status_led:
  pin:
    number: GPIO0
    inverted: yes

switch:
  - platform: gpio
    id: outlet
    name: "outlet Relay"
    pin: GPIO15
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: light1
    name: "light1 Relay"
    pin: GPIO4
    restore_mode: ALWAYS_OFF 
