substitutions:
  device_name: yamaha

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  on_boot: 
  - switch.turn_on: relay

wifi:
  ssid: !secret wifi_ssid
  password: !secret password

# Enable logging
logger:
  baud_rate: 0
  level: verbose

# Enable Home Assistant API
api:

ota:


uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff POW 01 Button"
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: "${device_name} Relay"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    output: pow_blue_led
    id: led

sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${device_name} Uptime"
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    update_interval: 2s
    current:
      name: "${device_name} Current"
    voltage:
      name: "${device_name} Voltage"
    power:
      name: "${device_name} Power"
  
      
