kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant
  namespace: home
  labels:
    type: host
spec:
  # set to empty to disable dynamic provisioning using StorageClass
  storageClassName: "homeassistant"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
