apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: smart-home
spec:
  selector:
    app: homeassistant
  ports:
    - name: homeasssitant
      protocol: TCP
      port: 80
      targetPort: 8123
  type: LoadBalancer
