apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
spec:
  storageClassName: "homeassistant"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/docker/homeassistant2"
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: hostvol2
# spec:
#   storageClassName: "fast-and-furious"
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/volumes/vol2"