apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-homeassistant
  namespace: smart-home
  labels: 
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: homeassistant/amd64-homeassistant:0.115.6
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: version
          value: 0.115.6.0 
        ports:
        - containerPort: 8123
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - mountPath: /config
          name: homeassistant
      volumes:
      - name: homeassistant
        persistentVolumeClaim:
          claimName: homeassistant

