apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels: 
    app: homeassistant
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: rollingUpdate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:0.112.0
        ports:
        - containerPort: 8123
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 15
          periodSeconds: 3
        volumeMounts:
        - mountPath: /config
          name: homeassistant
      volumes:
      - name: homeassistant
        persistentVolumeClaim:
          claimName: homeassistant
