name: Sync Home Assistant Config

on:
  push:
    branches:
      - master 

jobs:
  sync_files_k8s:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
        echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

    - name: Get Pod Name
      run: |
        export POD_NAME=$(kubectl get pods -l app=homeassistant -n smart-home -o jsonpath='{.items[0].metadata.name}')
        echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV

    - name: Identify and Copy Changed Files to Volume
      run: |
        current_dir=$(pwd)
        changed_files=$(git diff HEAD~1 --name-only)
        for file in $changed_files; do
          if [[ $file == config/* ]]; then
            dest_path="/config/$(dirname $file)"
            full_path="$current_dir/$file"
            echo "Copying file from: $full_path to: $dest_path"        
            kubectl cp $full_path smart-home/$POD_NAME:$dest_path -c homeassistant -n smart-home || exit 1
          else
            echo "Skipping file: $file"
          fi
        done
  validate_and_reload:
    needs: sync_files_k8s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set environment variables
        run: |
          echo "HASS_SERVER=${{ secrets.HASS_SERVER }}" >> $GITHUB_ENV

      - name: Install hass-cli
        run: |
          curl -Lo hass-cli https://github.com/home-assistant/cli/releases/download/4.27.0/ha_amd64
          chmod +x hass-cli
          sudo mv hass-cli /usr/local/bin/
      
      - name: Validate configuration
        run: |
          response=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.HASS_TOKEN }}" -H "Content-Type: application/json" ${{ secrets.HASS_SERVER }}/api/config/core/check_config)
          echo "Validation Response: $response"
          if [[ $response == *'"result":"valid"'* ]]; then
            echo "Configuration is valid, proceeding to reload."
          else
            echo "Configuration validation failed, aborting."
            exit 1
          fi
      
      - name: Identify and Copy Changed Files to Volume
        run: |
            hass-cli service call homeassistant.reload_core_config
